export const arrAutorità = [
    "-",
    "Corte Costituzionale",
    "Cassazione civile",
    "Cassazione penale",
    "Consiglio di Stato",
    "T.A.R.",
    "Tribunale",
    "Arbitro bancario finanziario",
    "Aut. en. elettrica e gas",
    "Aut. protez. dati person.",
    "Collegio arbitrale",
    "Collegio centr. garanzia elettorale",
    "Comm. appello F.I.G.C.",
    "Commissione centrale sanità",
    "Commissione elettorale",
    "Comm. gar. l. sciopero SS.PP.",
    "Comm. ricorsi brevetti",
    "Comm. Trib I grado Trentino Alto Adige",
    "Comm. Trib II grado Trentino Alto Adige",
    "Comm. trib. centr.",
    "Comm. trib. prov.le",
    "Comm. trib. prov-distr.",
    "Comm. trib. reg.",
    "Commissione usi civici",
    "Cons. giust. amm. Sicilia",
    "Cons. Naz.le Forense",
    "Cons. Naz.le Geometri",
    "Cons. Sup. Magistratura",
    "Consiglio di Stato ad. gen.",
    "Consiglio di Stato ad. plen.",
    "Consiglio di Stato atti norm.",
    "Consiglio di Stato comm. spec.",
    "Corte appello",
    "Corte assise",
    "Corte assise appello",
    "Corte Conti",
    "Corte europea diritti dell'uomo",
    "Corte di giustizia UE",
    "Corte int.le giustizia",
    "Corte militare appello",
    "Corte penale internazionale",
    "Garante concorr. e mercato",
    "Garante editoria",
    "Giudice conciliatore",
    "Giudice di pace",
    "Giudice istruttore",
    "Giudice tutelare",
    "Giurì cod. aut. pubb.ria",
    "Lodo arbitrale",
    "Ministero del lavoro",
    "Ministero delle finanze",
    "Prefettura",
    "Pretura",
    "Procura della Repubblica",
    "Procura gen. Corte appello",
    "Sacra Rota",
    "Tribunale della funzione pubblica UE",
    "Tribunale I grado UE",
    "Tribunale minorenni",
    "Tribunale regionale delle acque",
    "Tribunale regionale Canonico",
    "Tribunale superiore delle acque",
    "Tribunale superiore militare",
    "Ufficio centrale referendum",
    "Ufficio europeo brevetti",
    "Vicariato Urbe"
]

export const arrCodice = [
    "-",
    "Codice Civile",
    "Codice di Procedura Civile",
    "Codice Penale",
    "Codice di Procedura Penale",
    "Codice della Navigazione",
    "Costituzione della Repubblica",
    "Codice Penale Militare di Guerra",
    "Codice Penale Militare di Pace",
    "Disp. Att. Codice Procedura Penale",
    "Disp. Att. Trans. Codice Civile",
    "Disp. Att. Trans. Codice Procedura Civile",
    "Disp. Coord. Trans. Att. Codici Penali Militari",
    "Disp. Coord. Trans. Codice Penale",
    "Disposizioni finali della Costituzione",
    "Disposizioni sulla legge in generale (Preleggi)",
    "Regolamento Codice della Navigazione",
    "Regolamento Codice Procedura Penale",
    "Regolamento per la navigazione interna"
]

export const arrSottonumero = [
    "bis",
    "ter",
    "quater",
    "quinquies",
    "sexies",
    "septies",
    "octies",
    "nonies",
    "decies",
    "undecies",
    "duodecies",
    "terdecies",
    "quaterdecies",
    "quinquiesdecies",
    "sexiesdecies",
    "septiesdecies",
    "octiesdecies",
    "noviesdecies",
    "vicies",
    "vicies semel",
    "vicies bis",
    "vicies ter",
    "vicies quater",
    "vicies quinquies",
    "vicies sexies",
    "vicies septies",
    "duodetricies",
    "undetricies",
    "tricies",
    "tricies semel",
    "tricies bis",
    "tricies ter",
    "tricies quater"
]

export const arrLegge = [
    "-",
    "Circolari ministeriali",
    "Contratti collettivi",
    "Decreti ministeriali",
    "Leggi dello Stato",
    "Leggi provinciali",
    "Leggi regionali",
    "Provvedimenti CE",
    "Trattati internazionali",
]

export const arrProvvedimento = [
    "-",
    "Legge",
    "Decreto Legge",
    "Decreto legislativo",
    "Decreto del Presidente della Repubblica",
    "Decreto ministeriale",
    "Accordo",
    "Autorita' per la vigilanza sui lavori pubblici",
    "Avviso",
    "Azienda di stato per interventi nel mercato agricolo",
    "Bando",
    "Camera dei Deputati",
    "Comitato interm. Politica Industriale",
    "Comitato interm. Prezzi",
    "Comitato interm. Programmazione Economica",
    "Comitato interm. Programmazione Economica e Trasporti",
    "Commissione Nazionale per la Societa'  e la Borsa",
    "Comunicato della Presidenza Consiglio dei Ministri",
    "Comunicazione",
    "Corte Suprema di Cassazione",
    "Costituzione della Repubblica italiana",
    "Decreto",
    "Decreto Alto Commissario Alimentazione",
    "Decreto Alto Commissario Igiene e Sanita' pubblica",
    "Decreto del Capo del Governo",
    "Decreto del Capo provvisorio dello Stato",
    "Decreto del Commissario",
    "Decreto del Duce",
    "Decreto del Presidente del Consiglio dei Ministri",
    "Decreto del Presidente del Senato della Repubblica",
    "Decreto del Presidente della Camera dei Deputati",
    "Decreto dell'Assessore",
    "Decreto interministeriale",
    "Decreto Legge del Capo provvisorio dello Stato",
    "Decreto Legge luogotenenziale",
    "Decreto legislativo del Capo provvisorio dello Stato",
    "Decreto legislativo del Presidente del Consiglio",
    "Decreto legislativo luogotenenziale",
    "Decreto luogotenenziale",
    "Delibera del Senato della Repubblica",
    "Delibera della Camera dei Deputati",
    "Deliberazione",
    "Deliberazione della Corte costituzionale",
    "Determinazione",
    "Direttiva del Presidente del Consiglio dei Ministri",
    "Direttiva ministeriale",
    "Disposizione",
    "Documento",
    "Garante per i dati personali",
    "Garante per l'antitrust",
    "Garante per le telecomunicazioni",
    "Garante per l'editoria",
    "Garante per l'energia elettrica e il gas",
    "Istituto centrale di statistica",
    "Legge costituzionale",
    "Ministero degli affari esteri",
    "Ministero dei trasporti",
    "Ministero del lavoro e della previdenza sociale",
    "Ministero del tesoro",
    "Ministero della protezione civile",
    "Ministero della sanita'",
    "Ministero dell'agricoltura",
    "Ministero dell'industria commercio e artigianato",
    "Ordinanza",
    "Ordinanza Alto Commissario Igiene e Sanita' pubblica",
    "Ordinanza del Presidente del Consiglio dei Ministri",
    "Ordinanza ministeriale",
    "Provvedimento",
    "Regio decreto",
    "Regio Decreto Legge",
    "Regio Decreto Legislativo",
    "Regolamento",
    "Regolamento del Consiglio Superiore Magistratura",
    "Regolamento del Senato della Repubblica",
    "Regolamento della Camera dei Deputati",
    "Regolamento della Corte costituzionale",
    "Regolamento parlamentare",
    "Senato della Repubblica"
]

export const arrCategoriaProvvedimento = [
    "-",
    "Aborto",
    "Accordi di Villa Madama",
    "Accordo di Schengen",
    "Adozione e affidamento",
    "Adozione internazionale",
    "Adozione speciale",
    "Affidamento condiviso",
    "Agevolazioni tributarie (disciplina)",
    "Amato",
    "Antimafia",
    "Antiriciclaggio",
    "Antitrust (concorrenza)",
    "Artbonus",
    "Attività di governo (disciplina)",
    "Barriere architettoniche ",
    "Basaglia",
    "Bassanini",
    "Bassanini bis",
    "Bassanini quater",
    "Bassanini ter",
    "Bersani (liberalizzazioni)",
    "Bersani bis",
    "Biagi",
    "Biotestamento",
    "Bossi - Fini",
    "Bucalossi",
    "Carbon tax",
    "Carotti",
    "Carta europea dell'autonomia locale",
    "Catasto",
    "Categorie protette",
    "Cirami",
    "Cittadinanza",
    "Codice antimafia",
    "Codice dei beni culturali e paesaggio",
    "Codice dei contratti pubblici",
    "Codice dei lavori pubblici",
    "Codice del consumo",
    "Codice del processo amministrativo",
    "Codice del terzo settore",
    "Codice del Turismo",
    "Codice della crisi d'impresa e dell'insolvenza",
    "Codice della giustizia contabile",
    "Codice della nautica da diporto",
    "Codice della proprietà industriale ",
    "Codice della strada (nuovo)",
    "Codice dell'ambiente",
    "Codice dell'amministrazione digitale",
    "Codice delle assicurazioni private",
    "Codice delle comunicazioni elettroniche",
    "Codice delle pari opportunità",
    "Codice dell'ordinamento militare ",
    "Codice postale",
    "Codice privacy",
    "Codice rosso",
    "Collaboratori di giustizia",
    "Collegato lavoro",
    "Concessioni governative",
    "Confidi",
    "Conflitto di interessi",
    "Consob",
    "Contratti di solidarietà",
    "Conv. affidamento e sottrazione di minori",
    "Conv. di Bruxelles decisioni in materia civile e commerciale",
    "Conv. diritti fanciullo (New York)",
    "Conv. Europea Diritti dell'Uomo",
    "Conv. Ginevra (prigionieri di guerra)",
    "Conv. Italia - Santa Sede in materia fiscale",
    "Conv. mutua assistenza e cooperazione tra amministrazioni doganali",
    "Conv. New York eliminazione discriminazione razziale",
    "Conv. ONU diritti disabili",
    "Conv. ONU diritto del mare (Montego Bay)",
    "Conv. Oviedo sulla biomedicina e divieto clonazione",
    "Conv. Parigi doping nello sport",
    "Conv. Strasburgo assistenza giudiziaria in materia penale",
    "Conv. Vienna diritto dei trattati tra Stati e OI o tra OI",
    "Conv. Vienna sul diritto dei trattati",
    "Coronavirus - Covid-19",
    "Crescitalia 1",
    "Crescitalia 2",
    "Decreto agosto",
    "Decreto Cashback",
    "Decreto Cio",
    "Decreto clima",
    "Decreto Covid",
    "Decreto crescita",
    "Decreto cultura",
    "Decreto Cura Italia - Covid-19",
    "Decreto del fare",
    "Decreto dignità",
    "Decreto fiscale 2018",
    "Decreto fiscale 2019",
    "Decreto IRPEF",
    "Decreto liquidità - Covid-19",
    "Decreto Rifiuti",
    "Decreto Rilancio - Covid-19",
    "Decreto Ristori",
    "Decreto Ristori bis",
    "Decreto Ristori quater",
    "Decreto Ristori ter",
    "Decreto Sanità – Decreto Balduzzi",
    "Decreto scuola - Covid-19",
    "Decreto semplificazioni 2018",
    "Decreto semplificazioni 2020",
    "Decreto sicurezza",
    "Decreto sicurezza bis",
    "Decreto Sostegni",
    "Decreto Sviluppo",
    "Depenalizzazione",
    "Depenalizzazione reati minori",
    "Devolution",
    "Dini (Riforma delle pensioni)",
    "Direttiva whistleblowing",
    "Diritto d'autore",
    "Diritto Internazionale Privato (riforma)",
    "Disabili",
    "Divorzio (Fortuna - Baslini)",
    "Divorzio breve",
    "DL Covid",
    "Dpcm Natale 2020",
    "Editoria",
    "Elezioni Camera dei Deputati",
    "Elezioni dirette Consigli Regionali",
    "Elezioni Senato",
    "Equo canone",
    "Euro",
    "Ex Cirielli",
    "Factoring internazionale",
    "Fallimento - Legge fallimentare",
    "Famiglia (riforma)",
    "Federalismo demaniale",
    "Federalismo fiscale",
    "Federalismo fiscale municipale ",
    "Finanza locale",
    "Finanziaria 2010",
    "Finanziaria 2011 (Legge di stabilità)",
    "Finanziaria 2012 (Legge di stabilità)",
    "Finanziaria 2013 (Legge di stabilità)",
    "Finanziaria 2014 (Legge di stabilità)",
    "Finanziaria 2015 (Legge di stabilità) ",
    "Finanziaria 2016 (Legge di stabilità)",
    "Finanziaria 2017 (Legge di stabilità)",
    "Finanziaria 2018 (Legge di stabilità)",
    "Finanziaria 2019 (Legge di stabilità)",
    "Finanziaria 2020 (Legge di stabilità)",
    "Finanziaria 2021 (Legge di stabilità)",
    "Finanziaria triennale",
    "Fondi pensione",
    "Formica",
    "Franchising",
    "Fusioni transfrontaliere",
    "Gasparri",
    "Gelmini",
    "Giudice di pace",
    "Giudice di pace (competenza penale)",
    "Giudice Unico",
    "Goria",
    "Gozzini",
    "Grandi rischi",
    "Green economy",
    "Ici",
    "Impatto ambientale",
    "Impiegati civili dello Stato",
    "Imposta di bollo",
    "Imposta di registro",
    "Imposta di successioni e donazioni",
    "Imposte ipotecaria e catastale",
    "IMU",
    "Indultino",
    "Indulto",
    "Infortuni sul lavoro",
    "Inquinamento elettromagnetico",
    "Intercettazioni telefoniche",
    "Ipab",
    "Irap",
    "Italicum",
    "IVA",
    "Job Acts",
    "Leasing finanziario internazionale",
    "Legge Anticorruzione",
    "Legge Brunetta",
    "Legge comunitaria 2018",
    "Legge Gelli - Bianco",
    "Legge La Loggia",
    "Legge Levi",
    "Legge notarile ",
    "Legge Pinto",
    "Legge ponte urbanistica",
    "Legge Severino",
    "Legittima difesa",
    "Legittimo impedimento",
    "Locazioni (riforma)",
    "Lodo Alfano",
    "Lunardi (infrastrutture)",
    "Maggiore età",
    "Mammì",
    "Mancino",
    "Mandato di arresto europeo",
    "Manette agli evasori",
    "Manovra bis",
    "Manovra economica 1 - Decreto anticrisi",
    "Manovra economica 2 ",
    "Martelli",
    "Marzano",
    "Mediazione civile",
    "Merlin",
    "Milleproroghe ",
    "Milleproroghe 2013",
    "Milleproroghe 2017",
    "Milleproroghe 2021",
    "Minori a rischio",
    "Monitoraggio fiscale ",
    "Moratti",
    "Mosca",
    "NASPI",
    "Nazioni Unite (Statuto)",
    "Nicolazzi",
    "Notificazione atti giudiziari",
    "Nuovi compensi professionisti",
    "Nuovo Coronavirus - Covid-19",
    "Omicidio stradale",
    "Ordinamento giudiziario",
    "Ordinamento penitenziario (riforma)",
    "Organizzazione Mondiale del Commercio",
    "P2 (Anselmi)",
    "Pacchetto Lavoro - Giovannini",
    "Pacchetto sicurezza",
    "Par condicio",
    "Patente europea",
    "Patti Lateranensi",
    "Pecorella",
    "Pentiti",
    "Prestigiacomo (tratta di persone)",
    "Processo civile, amministrativo e Corte dei Conti (strumenti telematici)",
    "Processo penale minorenni",
    "Processo tributario ",
    "Procreazione assistita",
    "Prodi bis",
    "Province (abolizione)",
    "Quadri intermedi",
    "Reati tributari",
    "Reddito di cittadinanza - Quota 100",
    "Referendum",
    "Responsabilità amministrativa persone giuridiche",
    "Responsabilità civile dei magistrati",
    "Riconoscimento figli naturali",
    "Riforma del condominio",
    "Riforma Fornero - Riforma del mercato del lavoro ",
    "Riforma professione forense ",
    "Riforma Sanitaria",
    "Riforma sistema fiscale statale",
    "Riforma tributaria (legge delega)",
    "Riscossione delle imposte sui redditi",
    "Rogatorie",
    "Rognoni - La Torre",
    "Ronchey",
    "Sabatini",
    "Salvacalcio",
    "Salva-Italia",
    "Salvaleggi",
    "Salvaleggi 2",
    "Sblocca cantieri",
    "Sblocca Italia",
    "Scelba (organi regionali)",
    "Scelba (ricostituzione partito fascista)",
    "Schifani",
    "SCIA 2",
    "Sciopero nei servizi pubblici",
    "Scudo fiscale ",
    "Scuola dell'obbligo",
    "Seggiolini anti abbandono",
    "Semplificazione 2012",
    "Semplificazione dei riti",
    "Semplificazione fiscale",
    "Semplificazione normativa (Taglia-leggi, Calderoli)",
    "Sicurezza cibernetica",
    "Sicurezza e segreto di Stato",
    "SIM",
    "Simeone",
    "Sismica",
    "Smuraglia",
    "Spending review",
    "Sport (doping)",
    "Sport (scommesse e frode sportiva - Totonero)",
    "Stalking",
    "Stampa",
    "Stato civile",
    "Statuto dei lavoratori",
    "Statuto diritti dei contribuenti",
    "Superprocura",
    "Svuota carceri",
    "T.A.R. (istituzione)",
    "T.U. apprendistato ",
    "T.U. bancario (TUB)",
    "T.U. casellario giudiziario",
    "T.U. debito pubblico",
    "T.U. delle disposizioni regolamentari in materia di ordinamento militare",
    "T.U. disposizioni legislative in materia doganale",
    "T.U. documentazione amministrativa",
    "T.U. edilizia",
    "T.U. elettorato attivo",
    "T.U. elezioni comunali",
    "T.U. enti locali",
    "T.U. espropriazione per pubblica utilità",
    "T.U. Finanza  - T.U.F. Draghi",
    "T.U. Immigrazione (Turco - Napolitano)",
    "T.U. imposte dirette",
    "T.U. istruzione",
    "T.U. Leggi di pubblica sicurezza (T.U.L.P.S)",
    "T.U. Leggi sanitarie",
    "T.U. materia valutaria",
    "T.U. Promulgazione delle leggi",
    "T.U. Radiotelevisione",
    "T.U. sostegno maternità e paternità",
    "T.U. spese di giustizia ",
    "T.U. stupefacenti (Jervolino - Vassalli)",
    "T.U.I.R. imposte sui redditi",
    "Taglio dei parlamentari",
    "Tognoli",
    "Trapianti di organi",
    "Trasparenza atti amministrativi",
    "Trattamento Pensione di anzianità",
    "Trattato di Lisbona",
    "Tremonti",
    "Tremonti bis",
    "Treu",
    "Tribunale della libertà",
    "Tribunale minorenni",
    "Trust ",
    "Turismo sessuale (norme contro)",
    "Tutela del risparmio",
    "Unioni civili",
    "Urbani (salva cinema)",
    "Usura",
    "Vanoni",
    "Violenza negli stadi)",
    "Violenza sessuale",
    "Visentini ter",
    "Visto pesante",
    "Volontariato",
    "Voluntary disclosure 1",
    "Voluntary disclosure 2",
    "Whisteblowing"
]

export const arrFormulario = [
    "-",
    "Form. Tributario",
    "Form. Processo Amministrativo",
    "Form. Agrario",
    "Form. Condominio",
    "Form. Contratti",
    "Form. Locazioni",
    "Form. Esecuzioni",
    "Form. Richiesta pagamenti",
    "Form. Appalti",
    "Form. Lavoro",
    "Form. Società",
    "Form. Atti Penali      ",
    "Form. Processo Civile",
    "Form. Crisi d'Impresa",
    "Form. Responsabilità Civile",
    "Form. Famiglia",
]