export const arrAutorità = [
    "-",
    "Corte Costituzionale",
    "Cassazione civile",
    "Cassazione penale",
    "Consiglio di Stato",
    "T.A.R.",
    "Tribunale",
    "Arbitro bancario finanziario",
    "Aut. en. elettrica e gas",
    "Aut. protez. dati person.",
    "Collegio arbitrale",
    "Collegio centr. garanzia elettorale",
    "Comm. appello F.I.G.C.",
    "Commissione centrale sanità",
    "Commissione elettorale",
    "Comm. gar. l. sciopero SS.PP.",
    "Comm. ricorsi brevetti",
    "Comm. Trib I grado Trentino Alto Adige",
    "Comm. Trib II grado Trentino Alto Adige",
    "Comm. trib. centr.",
    "Comm. trib. prov.le",
    "Comm. trib. prov-distr.",
    "Comm. trib. reg.",
    "Commissione usi civici",
    "Cons. giust. amm. Sicilia",
    "Cons. Naz.le Forense",
    "Cons. Naz.le Geometri",
    "Cons. Sup. Magistratura",
    "Consiglio di Stato ad. gen.",
    "Consiglio di Stato ad. plen.",
    "Consiglio di Stato atti norm.",
    "Consiglio di Stato comm. spec.",
    "Corte appello",
    "Corte assise",
    "Corte assise appello",
    "Corte Conti",
    "Corte europea diritti dell'uomo",
    "Corte di giustizia UE",
    "Corte int.le giustizia",
    "Corte militare appello",
    "Corte penale internazionale",
    "Garante concorr. e mercato",
    "Garante editoria",
    "Giudice conciliatore",
    "Giudice di pace",
    "Giudice istruttore",
    "Giudice tutelare",
    "Giurì cod. aut. pubb.ria",
    "Lodo arbitrale",
    "Ministero del lavoro",
    "Ministero delle finanze",
    "Prefettura",
    "Pretura",
    "Procura della Repubblica",
    "Procura gen. Corte appello",
    "Sacra Rota",
    "Tribunale della funzione pubblica UE",
    "Tribunale I grado UE",
    "Tribunale minorenni",
    "Tribunale regionale delle acque",
    "Tribunale regionale Canonico",
    "Tribunale superiore delle acque",
    "Tribunale superiore militare",
    "Ufficio centrale referendum",
    "Ufficio europeo brevetti",
    "Vicariato Urbe"
]

export const arrCodice = [
    "-",
    "Codice antimafia",
    "Codice civile",
    "Codice dei beni culturali e del paesaggio",
    "Codice dei contratti pubblici",
    "Codice del consumo",
    "Codice del processo amministrativo",
    "Codice del processo tributario",
    "Codice del terzo settore",
    "Codice del turismo",
    "Codice della crisi d’impresa e dell’insolvenza",
    "Codice della nautica da diporto",
    "Codice della navigazione",
    "Codice della proprietà industriale",
    "Codice della protezione civile",
    "Codice della sicurezza in ambito lavorativo",
    "Codice della strada",
    "Codice delle assicurazioni private",
    "Codice delle comunicazioni elettroniche",
    "Codice delle pari opportunità",
    "Codice dell’ambiente",
    "Codice dell’amministrazione digitale",
    "Codice dell’ordinamento militare",
    "Codice di giustizia contabile",
    "Codice di procedura civile",
    "Codice di procedura penale",
    "Codice in materia di protezione dei dati personali",
    "Codice penale",
    "Codice penale militare di guerra",
    "Codice penale militare di pace"
]

export const arrSottonumero = [
    "bis",
    "ter",
    "quater",
    "quinquies",
    "sexies",
    "septies",
    "octies",
    "nonies",
    "decies",
    "undecies",
    "duodecies",
    "terdecies",
    "quaterdecies",
    "quinquiesdecies",
    "sexiesdecies",
    "septiesdecies",
    "octiesdecies",
    "noviesdecies",
    "vicies",
    "vicies semel",
    "vicies bis",
    "vicies ter",
    "vicies quater",
    "vicies quinquies",
    "vicies sexies",
    "vicies septies",
    "duodetricies",
    "undetricies",
    "tricies",
    "tricies semel",
    "tricies bis",
    "tricies ter",
    "tricies quater"
]

export const arrLegge = [
    "-",
    "Circolari ministeriali",
    "Contratti collettivi",
    "Decreti ministeriali",
    "Leggi dello Stato",
    "Leggi provinciali",
    "Leggi regionali",
    "Provvedimenti CE",
    "Trattati internazionali",
]

export const arrProvvedimento = [
    { label: "Accordo", tag: "Acc." },
    { label: "Avviso", tag: "Avv." },
    { label: "Decreto Legge", tag: "D.L." },
    { label: "Decreto legislativo", tag: "D.Lgs." },
    { label: "Decreto del Presidente della Repubblica", tag: "D.P.R." },
    { label: "Decreto ministeriale", tag: "D.M." },
    { label: "Bando", tag: "Bando" },
    { label: "Comunicato della Presidenza Consiglio dei Ministri = Com. P.C.M.", tag: "Com. P.C.M." },
    { label: "Comunicazione", tag: "Com" },
    { label: "Costituzione della Repubblica italiana", tag: "Cost." },
    { label: "Decreto", tag: "Decr." },
    { label: "Decreto Alto Commissario Alimentazione", tag: "Decr. A.C.A." }, //[Memo] Non mi va di contattare Luigi solo per questo, ma qui c'era scritto solo "Decr." come tag.
    { label: "Decreto Alto Commissario Igiene e Sanita' pubblica", tag: "Decr. A.C.I.S.P." }, //[Memo] Non mi va di contattare Luigi solo per questo, ma qui c'era scritto solo "Decr." come tag.
    { label: "Decreto del Capo del Governo", tag: "D.C.G." },
    { label: "Decreto del Capo provvisorio dello Stato", tag: "D.C.P.S." },
    { label: "Decreto del Commissario", tag: "Decr. Comm." },
    { label: "Decreto del Duce", tag: "Decr. Duce" },
    { label: "Decreto del Presidente del Consiglio dei Ministri", tag: "D.P.C.M." },
    { label: "Decreto del Presidente del Senato della Repubblica", tag: "Decr. Pres. Senato" },
    { label: "Decreto del Presidente della Camera dei Deputati", tag: "Decr. Pres. Camera" },
    { label: "Decreto dell'Assessore", tag: "Decr. Ass." },
    { label: "Decreto interministeriale", tag: "D.int." },
    { label: "Decreto Legge del Capo provvisorio dello Stato", tag: "D.L.C.P.S." },
    { label: "Decreto Legge luogotenenziale", tag: "D.L.L." },
    { label: "Decreto legislativo del Capo provvisorio dello Stato", tag: "D.Lgs.C.P.S." },
    { label: "Decreto legislativo luogotenenziale", tag: "D.Lgs.L." },
    { label: "Decreto luogotenenziale", tag: "D.Lt." },
    { label: "Delibera del Senato della Repubblica", tag: "Db Senato" },
    { label: "Delibera della Camera dei Deputati", tag: "Db Camera" },
    { label: "Deliberazione", tag: "Delib." },
    { label: "Deliberazione della Corte costituzionale", tag: "Delib. Corte cost." },
    { label: "Determinazione", tag: "Determ." },
    { label: "Direttiva del Presidente del Consiglio dei Ministri", tag: "Dir. P.C.M." },
    { label: "Direttiva ministeriale", tag: "Dir. min." },
    { label: "Disposizione", tag: "Disp." },
    { label: "Documento", tag: "Doc." },
    { label: "Legge", tag: "L." },
    { label: "Legge costituzionale", tag: "L. cost." },
    { label: "Ordinanza", tag: "Ord." },
    { label: "Ordinanza Alto Commissario Igiene e Sanità pubblica", tag: "Ord. A.C.I.S.P." }, //[Memo] Non mi va di contattare Luigi solo per questo, ma qui c'era scritto solo "Ord." come tag.
    { label: "Ordinanza del Presidente del Consiglio dei Ministri", tag: "Ord. P.C.M." },
    { label: "Ordinanza ministeriale", tag: "Ord. min." },
    { label: "Provvedimento", tag: "Provv." },
    { label: "Regio decreto", tag: "R.D." },
    { label: "Regio Decreto Legge", tag: "R.D.L." },
    { label: "Regio Decreto Legislativo", tag: "R.D.Lgs." },
    { label: "Regolamento", tag: "Reg." },
    { label: "Regolamento del Consiglio Superiore Magistratura", tag: "Reg. CSM" },
    { label: "Regolamento del Senato della Repubblica", tag: "Reg. Senato" },
    { label: "Regolamento della Camera dei Deputati", tag: "Reg. Camera" },
    { label: "Regolamento della Corte costituzionale", tag: "Reg. Corte cost." },
    { label: "Regolamento parlamentare", tag: "Reg. Parl." }
]

export const arrCategoriaProvvedimento = [
    "-",
    "Aborto",
    "Accordi di Villa Madama",
    "Accordo di Schengen",
    "Adozione e affidamento",
    "Adozione internazionale",
    "Adozione speciale",
    "Affidamento condiviso",
    "Agevolazioni tributarie (disciplina)",
    "Amato",
    "Antimafia",
    "Antiriciclaggio",
    "Antitrust (concorrenza)",
    "Artbonus",
    "Attività di governo (disciplina)",
    "Barriere architettoniche ",
    "Basaglia",
    "Bassanini",
    "Bassanini bis",
    "Bassanini quater",
    "Bassanini ter",
    "Bersani (liberalizzazioni)",
    "Bersani bis",
    "Biagi",
    "Biotestamento",
    "Bossi - Fini",
    "Bucalossi",
    "Carbon tax",
    "Carotti",
    "Carta europea dell'autonomia locale",
    "Catasto",
    "Categorie protette",
    "Cirami",
    "Cittadinanza",
    "Codice antimafia",
    "Codice dei beni culturali e paesaggio",
    "Codice dei contratti pubblici",
    "Codice dei lavori pubblici",
    "Codice del consumo",
    "Codice del processo amministrativo",
    "Codice del terzo settore",
    "Codice del Turismo",
    "Codice della crisi d'impresa e dell'insolvenza",
    "Codice della giustizia contabile",
    "Codice della nautica da diporto",
    "Codice della proprietà industriale ",
    "Codice della strada (nuovo)",
    "Codice dell'ambiente",
    "Codice dell'amministrazione digitale",
    "Codice delle assicurazioni private",
    "Codice delle comunicazioni elettroniche",
    "Codice delle pari opportunità",
    "Codice dell'ordinamento militare ",
    "Codice postale",
    "Codice privacy",
    "Codice rosso",
    "Collaboratori di giustizia",
    "Collegato lavoro",
    "Concessioni governative",
    "Confidi",
    "Conflitto di interessi",
    "Consob",
    "Contratti di solidarietà",
    "Conv. affidamento e sottrazione di minori",
    "Conv. di Bruxelles decisioni in materia civile e commerciale",
    "Conv. diritti fanciullo (New York)",
    "Conv. Europea Diritti dell'Uomo",
    "Conv. Ginevra (prigionieri di guerra)",
    "Conv. Italia - Santa Sede in materia fiscale",
    "Conv. mutua assistenza e cooperazione tra amministrazioni doganali",
    "Conv. New York eliminazione discriminazione razziale",
    "Conv. ONU diritti disabili",
    "Conv. ONU diritto del mare (Montego Bay)",
    "Conv. Oviedo sulla biomedicina e divieto clonazione",
    "Conv. Parigi doping nello sport",
    "Conv. Strasburgo assistenza giudiziaria in materia penale",
    "Conv. Vienna diritto dei trattati tra Stati e OI o tra OI",
    "Conv. Vienna sul diritto dei trattati",
    "Coronavirus - Covid-19",
    "Crescitalia 1",
    "Crescitalia 2",
    "Decreto agosto",
    "Decreto Cashback",
    "Decreto Cio",
    "Decreto clima",
    "Decreto Covid",
    "Decreto crescita",
    "Decreto cultura",
    "Decreto Cura Italia - Covid-19",
    "Decreto del fare",
    "Decreto dignità",
    "Decreto fiscale 2018",
    "Decreto fiscale 2019",
    "Decreto IRPEF",
    "Decreto liquidità - Covid-19",
    "Decreto Rifiuti",
    "Decreto Rilancio - Covid-19",
    "Decreto Ristori",
    "Decreto Ristori bis",
    "Decreto Ristori quater",
    "Decreto Ristori ter",
    "Decreto Sanità – Decreto Balduzzi",
    "Decreto scuola - Covid-19",
    "Decreto semplificazioni 2018",
    "Decreto semplificazioni 2020",
    "Decreto sicurezza",
    "Decreto sicurezza bis",
    "Decreto Sostegni",
    "Decreto Sviluppo",
    "Depenalizzazione",
    "Depenalizzazione reati minori",
    "Devolution",
    "Dini (Riforma delle pensioni)",
    "Direttiva whistleblowing",
    "Diritto d'autore",
    "Diritto Internazionale Privato (riforma)",
    "Disabili",
    "Divorzio (Fortuna - Baslini)",
    "Divorzio breve",
    "DL Covid",
    "Dpcm Natale 2020",
    "Editoria",
    "Elezioni Camera dei Deputati",
    "Elezioni dirette Consigli Regionali",
    "Elezioni Senato",
    "Equo canone",
    "Euro",
    "Ex Cirielli",
    "Factoring internazionale",
    "Fallimento - Legge fallimentare",
    "Famiglia (riforma)",
    "Federalismo demaniale",
    "Federalismo fiscale",
    "Federalismo fiscale municipale ",
    "Finanza locale",
    "Finanziaria 2010",
    "Finanziaria 2011 (Legge di stabilità)",
    "Finanziaria 2012 (Legge di stabilità)",
    "Finanziaria 2013 (Legge di stabilità)",
    "Finanziaria 2014 (Legge di stabilità)",
    "Finanziaria 2015 (Legge di stabilità) ",
    "Finanziaria 2016 (Legge di stabilità)",
    "Finanziaria 2017 (Legge di stabilità)",
    "Finanziaria 2018 (Legge di stabilità)",
    "Finanziaria 2019 (Legge di stabilità)",
    "Finanziaria 2020 (Legge di stabilità)",
    "Finanziaria 2021 (Legge di stabilità)",
    "Finanziaria triennale",
    "Fondi pensione",
    "Formica",
    "Franchising",
    "Fusioni transfrontaliere",
    "Gasparri",
    "Gelmini",
    "Giudice di pace",
    "Giudice di pace (competenza penale)",
    "Giudice Unico",
    "Goria",
    "Gozzini",
    "Grandi rischi",
    "Green economy",
    "Ici",
    "Impatto ambientale",
    "Impiegati civili dello Stato",
    "Imposta di bollo",
    "Imposta di registro",
    "Imposta di successioni e donazioni",
    "Imposte ipotecaria e catastale",
    "IMU",
    "Indultino",
    "Indulto",
    "Infortuni sul lavoro",
    "Inquinamento elettromagnetico",
    "Intercettazioni telefoniche",
    "Ipab",
    "Irap",
    "Italicum",
    "IVA",
    "Job Acts",
    "Leasing finanziario internazionale",
    "Legge Anticorruzione",
    "Legge Brunetta",
    "Legge comunitaria 2018",
    "Legge Gelli - Bianco",
    "Legge La Loggia",
    "Legge Levi",
    "Legge notarile ",
    "Legge Pinto",
    "Legge ponte urbanistica",
    "Legge Severino",
    "Legittima difesa",
    "Legittimo impedimento",
    "Locazioni (riforma)",
    "Lodo Alfano",
    "Lunardi (infrastrutture)",
    "Maggiore età",
    "Mammì",
    "Mancino",
    "Mandato di arresto europeo",
    "Manette agli evasori",
    "Manovra bis",
    "Manovra economica 1 - Decreto anticrisi",
    "Manovra economica 2 ",
    "Martelli",
    "Marzano",
    "Mediazione civile",
    "Merlin",
    "Milleproroghe ",
    "Milleproroghe 2013",
    "Milleproroghe 2017",
    "Milleproroghe 2021",
    "Minori a rischio",
    "Monitoraggio fiscale ",
    "Moratti",
    "Mosca",
    "NASPI",
    "Nazioni Unite (Statuto)",
    "Nicolazzi",
    "Notificazione atti giudiziari",
    "Nuovi compensi professionisti",
    "Nuovo Coronavirus - Covid-19",
    "Omicidio stradale",
    "Ordinamento giudiziario",
    "Ordinamento penitenziario (riforma)",
    "Organizzazione Mondiale del Commercio",
    "P2 (Anselmi)",
    "Pacchetto Lavoro - Giovannini",
    "Pacchetto sicurezza",
    "Par condicio",
    "Patente europea",
    "Patti Lateranensi",
    "Pecorella",
    "Pentiti",
    "Prestigiacomo (tratta di persone)",
    "Processo civile, amministrativo e Corte dei Conti (strumenti telematici)",
    "Processo penale minorenni",
    "Processo tributario ",
    "Procreazione assistita",
    "Prodi bis",
    "Province (abolizione)",
    "Quadri intermedi",
    "Reati tributari",
    "Reddito di cittadinanza - Quota 100",
    "Referendum",
    "Responsabilità amministrativa persone giuridiche",
    "Responsabilità civile dei magistrati",
    "Riconoscimento figli naturali",
    "Riforma del condominio",
    "Riforma Fornero - Riforma del mercato del lavoro ",
    "Riforma professione forense ",
    "Riforma Sanitaria",
    "Riforma sistema fiscale statale",
    "Riforma tributaria (legge delega)",
    "Riscossione delle imposte sui redditi",
    "Rogatorie",
    "Rognoni - La Torre",
    "Ronchey",
    "Sabatini",
    "Salvacalcio",
    "Salva-Italia",
    "Salvaleggi",
    "Salvaleggi 2",
    "Sblocca cantieri",
    "Sblocca Italia",
    "Scelba (organi regionali)",
    "Scelba (ricostituzione partito fascista)",
    "Schifani",
    "SCIA 2",
    "Sciopero nei servizi pubblici",
    "Scudo fiscale ",
    "Scuola dell'obbligo",
    "Seggiolini anti abbandono",
    "Semplificazione 2012",
    "Semplificazione dei riti",
    "Semplificazione fiscale",
    "Semplificazione normativa (Taglia-leggi, Calderoli)",
    "Sicurezza cibernetica",
    "Sicurezza e segreto di Stato",
    "SIM",
    "Simeone",
    "Sismica",
    "Smuraglia",
    "Spending review",
    "Sport (doping)",
    "Sport (scommesse e frode sportiva - Totonero)",
    "Stalking",
    "Stampa",
    "Stato civile",
    "Statuto dei lavoratori",
    "Statuto diritti dei contribuenti",
    "Superprocura",
    "Svuota carceri",
    "T.A.R. (istituzione)",
    "T.U. apprendistato ",
    "T.U. bancario (TUB)",
    "T.U. casellario giudiziario",
    "T.U. debito pubblico",
    "T.U. delle disposizioni regolamentari in materia di ordinamento militare",
    "T.U. disposizioni legislative in materia doganale",
    "T.U. documentazione amministrativa",
    "T.U. edilizia",
    "T.U. elettorato attivo",
    "T.U. elezioni comunali",
    "T.U. enti locali",
    "T.U. espropriazione per pubblica utilità",
    "T.U. Finanza  - T.U.F. Draghi",
    "T.U. Immigrazione (Turco - Napolitano)",
    "T.U. imposte dirette",
    "T.U. istruzione",
    "T.U. Leggi di pubblica sicurezza (T.U.L.P.S)",
    "T.U. Leggi sanitarie",
    "T.U. materia valutaria",
    "T.U. Promulgazione delle leggi",
    "T.U. Radiotelevisione",
    "T.U. sostegno maternità e paternità",
    "T.U. spese di giustizia ",
    "T.U. stupefacenti (Jervolino - Vassalli)",
    "T.U.I.R. imposte sui redditi",
    "Taglio dei parlamentari",
    "Tognoli",
    "Trapianti di organi",
    "Trasparenza atti amministrativi",
    "Trattamento Pensione di anzianità",
    "Trattato di Lisbona",
    "Tremonti",
    "Tremonti bis",
    "Treu",
    "Tribunale della libertà",
    "Tribunale minorenni",
    "Trust ",
    "Turismo sessuale (norme contro)",
    "Tutela del risparmio",
    "Unioni civili",
    "Urbani (salva cinema)",
    "Usura",
    "Vanoni",
    "Violenza negli stadi)",
    "Violenza sessuale",
    "Visentini ter",
    "Visto pesante",
    "Volontariato",
    "Voluntary disclosure 1",
    "Voluntary disclosure 2",
    "Whisteblowing"
]

export const arrFormulario = [
    "-",
    "Form. Tributario",
    "Form. Processo Amministrativo",
    "Form. Agrario",
    "Form. Condominio",
    "Form. Contratti",
    "Form. Locazioni",
    "Form. Esecuzioni",
    "Form. Richiesta pagamenti",
    "Form. Appalti",
    "Form. Lavoro",
    "Form. Società",
    "Form. Atti Penali      ",
    "Form. Processo Civile",
    "Form. Crisi d'Impresa",
    "Form. Responsabilità Civile",
    "Form. Famiglia",
]

const arrCittàRaw = [
    "Vittoria",
    "Villa San Giovanni",
    "Villacidro",
    "Villabate",
    "Vibo Valentia",
    "Tricase",
    "Trecastagni",
    "Trapani",
    "Termini Imerese",
    "Taviano",
    "Taurisano",
    "Taurianova",
    "Siracusa",
    "Sinnai",
    "Siderno",
    "Sestu",
    "Selargius",
    "Scordia",
    "Scicli",
    "Sciacca",
    "Sant'Antioco",
    "San Leone Mosè",
    "San Giovanni la Punta",
    "San Giovanni in Fiore",
    "San Cataldo",
    "Sambiase",
    "Rossano Stazione",
    "Rosolini",
    "Rosarno",
    "Riposto",
    "Riesi",
    "Ribera",
    "Reggio Calabria",
    "Ravanusa",
    "Ramacca",
    "Ragusa",
    "Raffadali",
    "Quattromiglia",
    "Quartu Sant'Elena",
    "Quartucciu",
    "Priolo Gargallo",
    "Pozzallo",
    "Porto Empedocle",
    "Piazza Armerina",
    "Pellaro",
    "Pedara",
    "Paternò",
    "Partinico",
    "Partanna",
    "Paola",
    "Palmi",
    "Palma di Montechiaro",
    "Palermo",
    "Palagonia",
    "Pachino",
    "Oristano",
    "Noto",
    "Niscemi",
    "Nicosia",
    "Nicastro",
    "Monserrato",
    "Monreale",
    "Modica",
    "Misterbianco",
    "Misilmeri",
    "Milazzo",
    "Messina",
    "Menfi",
    "Mazzarino",
    "Mazara del Vallo",
    "Mascalucia",
    "Marsala",
    "Locri",
    "Licata",
    "Leonforte",
    "Lentini",
    "Ispica",
    "Isola di Capo Rizzuto",
    "Iglesias",
    "Guspini",
    "Grammichele",
    "Gioia Tauro",
    "Giarre",
    "Gela",
    "Francofonte",
    "Floridia",
    "Ficarazzi",
    "Favara",
    "Enna",
    "Crotone",
    "Cosenza",
    "Corleone",
    "Comiso",
    "Cirò Marina",
    "Cinisi",
    "Cefalù",
    "Catanzaro",
    "Catania",
    "Castrovillari",
    "Castelvetrano",
    "Castellammare del Golfo",
    "Casteldaccia",
    "Cassano Allo Ionio",
    "Casarano",
    "Carlentini",
    "Carini",
    "Carbonia",
    "Capoterra",
    "Capo d'Orlando",
    "Canicattì",
    "Campobello di Licata",
    "Caltanissetta",
    "Caltagirone",
    "Cagliari",
    "Bronte",
    "Biancavilla",
    "Belpasso",
    "Belmonte Mezzagno",
    "Barrafranca",
    "Barcellona Pozzo di Gotto",
    "Bagheria",
    "Avola",
    "Augusta",
    "Assemini",
    "Alcamo",
    "Agrigento",
    "Adrano",
    "Aci Sant'Antonio",
    "Acireale",
    "Aci Catena",
    "Aci Castello",
    "Zola Predosa",
    "Zevio",
    "Zagarolo",
    "Vomero",
    "Volpiano",
    "Voghera",
    "Vittorio Veneto",
    "Viterbo",
    "Vimodrone",
    "Vimercate",
    "Lancenigo-Villorba",
    "Villasanta",
    "Villaricca",
    "Villa Literno",
    "Villafranca di Verona",
    "Villa Carcina",
    "Vigonza",
    "Vignola",
    "Vigevano",
    "Vieste",
    "Vico Equense",
    "Vicenza",
    "Viareggio",
    "Viadana",
    "Vetralla",
    "Verona",
    "Vercelli",
    "Ventimiglia",
    "Venosa",
    "Venezia",
    "Venaria Reale",
    "Velletri",
    "Veglie",
    "Vasto",
    "Varese",
    "Varedo",
    "Varazze",
    "Valmontone",
    "Valmadrera-Caserta",
    "Valenzano",
    "Valenza",
    "Valdagno",
    "Umbertide",
    "Udine",
    "Turi",
    "Trofarello",
    "Trinitapoli",
    "Triggiano",
    "Trieste",
    "Trezzo sull'Adda",
    "Trezzano sul Naviglio",
    "Treviso",
    "Treviglio",
    "Trepuzzi",
    "Trentola-Ducenta",
    "Trento",
    "Trecate",
    "Travagliato",
    "Trani",
    "Tradate",
    "Tortona",
    "Torremaggiore",
    "Torre del Lago Puccini",
    "Torre del Greco",
    "Torre Annunziata",
    "Torino",
    "Tolentino",
    "Tivoli",
    "Thiene",
    "Terzigno",
    "Terracina",
    "Terni",
    "Termoli",
    "Terlizzi",
    "Teramo",
    "Tempio Pausania",
    "Tavagnacco",
    "Tarquinia",
    "Taranto",
    "Taglio",
    "Taggia",
    "Suzzara",
    "Surbo",
    "Sulmona",
    "Stradella",
    "Stezzano",
    "Statte",
    "Squinzano",
    "Spresiano",
    "Spoleto",
    "Sorso",
    "Sorrento",
    "Sora",
    "Sondrio",
    "Somma Vesuviana",
    "Somma Lombardo",
    "Solofra",
    "Solaro",
    "Solaro",
    "Soccavo",
    "Silvi",
    "Signa",
    "Siena",
    "Sezze",
    "Seveso",
    "Settimo Torinese",
    "Sestri Levante",
    "Sesto San Giovanni",
    "Sesto Fiorentino",
    "Seriate",
    "Seregno",
    "Senigallia",
    "Senago",
    "Segrate",
    "Sedriano",
    "Secondigliano",
    "Schio",
    "Scandicci",
    "Scandiano",
    "Scafati",
    "Savona",
    "Savignano sul Rubicone",
    "Savigliano",
    "Saviano",
    "Sava",
    "Sassuolo",
    "Sassari",
    "Sarzana",
    "Saronno",
    "Sarno",
    "Sarezzo",
    "San Vito dei Normanni",
    "San Vito al Tagliamento",
    "Santeramo in Colle",
    "Sant'Arpino",
    "Santarcangelo",
    "Sant'Antonio Abate",
    "Sant'Antonio",
    "Sant'Antimo",
    "Sant'Angelo Lodigiano",
    "Sant'Anastasia",
    "Sant'Ambrogio di Valpollicella",
    "Santa Marinella",
    "Santa Maria Capua Vetere",
    "Santa Maria A Vico",
    "Sant'Agata de'Goti",
    "Santa Croce sull'Arno",
    "San Severo",
    "Sansepolcro",
    "San Sebastiano",
    "San Salvo",
    "San Remo",
    "San Prisco",
    "San Pietro Vernotico",
    "San Pancrazio Salentino",
    "Sannicandro Garganico",
    "San Miniato",
    "San Miniato Basso",
    "San Mauro Torinese",
    "San Martino di Lupari",
    "San Martino Buon Albergo",
    "San Marco in Lamis",
    "San Lazzaro",
    "San Giuseppe Vesuviano",
    "San Giuliano Milanese",
    "San Giovanni Valdarno",
    "San Giovanni Rotondo",
    "San Giovanni Lupatoto",
    "San Giovanni in Persiceto",
    "San Giovanni a Teduccio",
    "San Giorgio Ionico",
    "San Giorgio a Cremano",
    "San Gennaro Vesuviano",
    "San Ferdinando di Puglia",
    "San Donato Milanese",
    "San Donà di Piave",
    "San Cesareo",
    "San Bonifacio",
    "San Benedetto del Tronto",
    "Samarate",
    "Saluzzo",
    "Salsomaggiore Terme",
    "Salerno",
    "Sala Consilina",
    "Sacile",
    "Ruvo di Puglia",
    "Rutigliano",
    "Rubiera",
    "Rozzano",
    "Rovigo",
    "Rovereto",
    "Rovato",
    "Rosignano Solvay-Castiglioncello",
    "Roseto degli Abruzzi",
    "Rosa",
    "Rosà",
    "Ronchi dei Legionari",
    "Romano di Lombardia",
    "Roma",
    "Rocca di Papa",
    "Rivoli",
    "Rivarolo Canavese",
    "Rivalta di Torino",
    "Riva del Garda",
    "Rionero in Vulture",
    "Rimini",
    "Rieti",
    "Riccione",
    "Rho",
    "Rezzato",
    "Rescaldina",
    "Reggio nell'Emilia",
    "Recanati",
    "Ravenna",
    "Rapallo",
    "Qualiano",
    "Putignano",
    "Procida",
    "Priverno",
    "Prato",
    "Pozzuoli",
    "Potenza",
    "Posillipo",
    "Porto Torres",
    "Porto Tolle",
    "Porto Sant'Elpidio",
    "Porto San Giorgio",
    "Porto Recanati",
    "Portogruaro",
    "Civitanova Marche",
    "Portici",
    "Pordenone",
    "Porcia",
    "Ponticelli",
    "Ponte San Pietro",
    "Ponte San Nicolò",
    "Pontedera",
    "Pontecagnano",
    "Ponsacco",
    "Pompei",
    "Pomigliano d'Arco",
    "Pomezia",
    "Polignano a Mare",
    "Policoro",
    "Poggioreale",
    "Poggiomarino",
    "Poggibonsi",
    "Pistoia",
    "Piscinola",
    "Pisa",
    "Piove di Sacco-Piovega",
    "Piossasco",
    "Piombino",
    "Pioltello",
    "Pinerolo",
    "Pietrasanta",
    "Piazza",
    "Pianura",
    "Piano di Sorrento",
    "Pianezza",
    "Piacenza",
    "Pescia",
    "Bettola-Zeloforomagno",
    "Pescara",
    "Pescantina",
    "Pesaro",
    "Perugia",
    "Pergine Valsugana",
    "Pavia",
    "Paullo",
    "Parma",
    "Parabiago",
    "Palo del Colle",
    "Palma Campania",
    "Palazzolo sull'Oglio",
    "Palestrina",
    "Palagiano",
    "Pagani",
    "Padova",
    "Paderno Dugnano",
    "Ottaviano",
    "Ostuni",
    "Ospitaletto",
    "Osimo",
    "Ortona",
    "Orta Nova",
    "Oria",
    "Orbassano",
    "Opera",
    "Omegna",
    "Olgiate Olona",
    "Olgiate Comasco",
    "Oleggio",
    "Olbia",
    "Oderzo",
    "Nuoro",
    "Novi Ligure",
    "Novellara",
    "Novate Milanese",
    "Novara",
    "Nova Milanese",
    "Nonantola",
    "Nola",
    "Noicattaro",
    "Noci",
    "Nocera Superiore",
    "Nocera Inferiore",
    "Noale",
    "Nichelino",
    "Nettuno",
    "Nerviano",
    "Nave",
    "Nardò",
    "Napoli",
    "Mugnano di Napoli",
    "Muggiò",
    "Muggia",
    "Mottola",
    "Mortara",
    "Morbegno",
    "Monza",
    "Montignoso",
    "Montichiari",
    "Montevarchi",
    "Montesilvano Marina",
    "Montesarchio",
    "Monte Sant'Angelo",
    "Monterotondo",
    "Monteroni di Lecce",
    "Montemurlo",
    "Montelupo Fiorentino",
    "Montegrotto Terme",
    "Montegranaro",
    "Montefiascone",
    "Monte di Procida",
    "Montecchio Maggiore-Alte Ceccato",
    "Montecatini-Terme",
    "Montebelluna",
    "Monsummano Terme",
    "Monselice",
    "Monopoli",
    "Monfalcone",
    "Mondragone",
    "Mondovì",
    "Moncalieri",
    "Molfetta",
    "Mola di Bari",
    "Mogliano Veneto",
    "Modugno",
    "Modena",
    "Mirano",
    "Mirandola",
    "Mira Taglio",
    "Minturno",
    "Milano",
    "Miano",
    "Mestre",
    "Mesagne",
    "Mercato San Severino",
    "Merate",
    "Merano",
    "Mentana",
    "Melzo",
    "Melito di Napoli",
    "Melfi",
    "Melegnano",
    "Meda",
    "Matino",
    "Matera",
    "Massarosa",
    "Massa Lubrense",
    "Massafra",
    "Massa",
    "Martinsicuro",
    "Martina Franca",
    "Marino",
    "Marina di Massa",
    "Marina di Carrara",
    "Marigliano",
    "Mariano Comense",
    "Margherita di Savoia",
    "Marcon-Gaggio-Colmello",
    "Marcianise",
    "Marano di Napoli",
    "Mantova",
    "Maniago",
    "Manfredonia",
    "Manerbio",
    "Manduria",
    "Mandello del Lario",
    "Malo",
    "Malnate",
    "Maglie",
    "Magenta",
    "Maddaloni",
    "Macomer",
    "Macerata Campania",
    "Macerata",
    "Luino",
    "Lugo",
    "Lucera",
    "Lucca",
    "Lonigo",
    "Lonate Pozzolo",
    "Lodi",
    "Loano",
    "Lizzano",
    "Livorno",
    "Lissone",
    "Limbiate",
    "Lido di Ostia",
    "Lido di Jesolo",
    "Lido",
    "Leverano",
    "Lentate sul Seveso",
    "Leno",
    "Leini",
    "Legnano",
    "Legnago",
    "Lecco",
    "Lecce",
    "Lavello",
    "Lavagna",
    "Latina",
    "Latiano",
    "Laterza",
    "Lastra a Signa",
    "La Spezia",
    "Lariano",
    "L'Aquila",
    "Lanciano",
    "La Maddalena",
    "Laives",
    "Lainate",
    "Ladispoli",
    "Ivrea",
    "Isola del Liri",
    "Isernia",
    "Ischia Porto",
    "Ischia",
    "Pallanza-Intra-Suna",
    "Induno Olona",
    "Imperia",
    "Imola",
    "Jesi",
    "Gussago",
    "Guidonia",
    "Gubbio",
    "Guastalla",
    "Grumo Nevano",
    "Grumo Appula",
    "Grugliasco",
    "Grottammare",
    "Grottaglie",
    "Grottaferrata",
    "Grosseto",
    "Gricignano di Aversa",
    "Gravina in Puglia",
    "Gragnano",
    "Gorizia",
    "Gorgonzola",
    "Giussano",
    "Giulianova",
    "Giugliano in Campania",
    "Giovinazzo",
    "Gioia del Colle",
    "Ginosa",
    "Giffoni Valle Piana",
    "Giaveno",
    "Ghedi",
    "Genzano di Roma",
    "Genova",
    "Gemona",
    "Gardone Val Trompia",
    "Garbagnate Milanese",
    "Gambettola",
    "Gallipoli",
    "Galliate",
    "Gallarate",
    "Galatone",
    "Galatina",
    "Gaeta",
    "Fuorigrotta",
    "Fucecchio",
    "Frosinone",
    "Frattaminore",
    "Frattamaggiore",
    "Frascati",
    "Francavilla Fontana",
    "Francavilla al Mare",
    "Fossano",
    "Fornacelle",
    "Formigine",
    "Formia",
    "Forlì",
    "Forio",
    "Fondi",
    "Follonica",
    "Foligno",
    "Foggia",
    "Fiumicino-Isola Sacra",
    "Firenze",
    "Fiorenzuola d'Arda",
    "Fiorano",
    "Figline Valdarno",
    "Fidenza",
    "Fiano Romano",
    "Ferrara",
    "Fermo",
    "Ferentino",
    "Feltre",
    "Fasano",
    "Fano",
    "Falconara Marittima",
    "Fagnano Olona-Bergoro",
    "Faenza",
    "Fabriano",
    "Este",
    "Ercolano",
    "Erba",
    "Empoli",
    "Eboli",
    "Dueville",
    "Domodossola",
    "Desio",
    "Desenzano del Garda",
    "Dalmine",
    "Cusano",
    "Cuneo",
    "Crispiano",
    "Cremona",
    "Crema",
    "Creazzo",
    "Cossato",
    "Corsico",
    "Correggio",
    "Cornaredo",
    "Cormano",
    "Cordenons",
    "Corbetta",
    "Corato",
    "Copertino",
    "Conversano",
    "Conegliano",
    "Concorezzo",
    "Como",
    "Cologno Monzese",
    "Cologno al Serio",
    "Collegno",
    "Colleferro",
    "Colle di Val d'Elsa",
    "Codroipo",
    "Codogno",
    "Civitavecchia",
    "Civita Castellana",
    "Città di Castello",
    "Cittadella",
    "Cisterna di Latina",
    "Ciriè",
    "Cinisello Balsamo",
    "Cicciano",
    "Ciampino",
    "Chivasso",
    "Chioggia",
    "Chieti",
    "Chieri",
    "Chiavari",
    "Chiari",
    "Chiaravalle",
    "Chiampo",
    "Cesenatico",
    "Cesena",
    "Cesano Maderno",
    "Cervignano del Friuli",
    "Cervia",
    "Cerveteri",
    "Certaldo",
    "Cerro Maggiore",
    "Cernusco sul Naviglio",
    "Cerignola",
    "Cerea",
    "Cercola",
    "Cento",
    "Ceglie Messapica",
    "Cecina",
    "Ceccano",
    "Cava Dè Tirreni",
    "Cattolica",
    "Castiglione delle Stiviere",
    "Castel Volturno",
    "Castel San Pietro Terme",
    "Castel San Giovanni",
    "Castelnovo ne'Monti",
    "Castel Mella",
    "Castel Maggiore",
    "Castellanza",
    "Castellaneta",
    "Castellana",
    "Castellammare di Stabia",
    "Castelfranco Veneto",
    "Castelfranco Emilia",
    "Castelfiorentino",
    "Castelfidardo",
    "Castano Primo",
    "Cassino",
    "Cassina de' Pecchi",
    "Cassano delle Murge",
    "Cassano d'Adda",
    "Casoria",
    "Caserta",
    "Caselle Torinese",
    "Cascina",
    "Casandrino",
    "Casamassima",
    "Casalpusterlengo",
    "Casalnuovo di Napoli",
    "Casalmaggiore",
    "Casale Monferrato",
    "Casalecchio di Reno",
    "Casal di Principe",
    "Carugate",
    "Carrara",
    "Carpi Centro",
    "Carpenedolo",
    "Carovigno",
    "Carmagnola",
    "Cardito",
    "Caravaggio",
    "Carate Brianza",
    "Capurso",
    "Capua",
    "Capannori",
    "Cantù",
    "Canosa di Puglia",
    "Canegrate",
    "Camponogara",
    "Campodarsego",
    "Campobasso",
    "Campi Salentina",
    "Campi Bisenzio",
    "Cameri",
    "Camaiore",
    "Calvizzano",
    "Calolziocorte",
    "Calenzano",
    "Caldogno-Rettorgole-Cresole",
    "Caivano",
    "Busto Garolfo",
    "Busto Arsizio",
    "Bussolengo",
    "Brusciano",
    "Brunico",
    "Brugherio",
    "Brindisi",
    "Bresso",
    "Bressanone",
    "Brescia",
    "Bracciano",
    "Bra",
    "Bovolone",
    "Bovisio-Masciago",
    "Boscotrecase",
    "Boscoreale",
    "Borgosesia",
    "Borgo San Dalmazzo",
    "Borgomanero",
    "Borgaro Torinese",
    "Bolzano",
    "Bologna",
    "Bollate",
    "Darfo Boario Terme",
    "Bitritto",
    "Bitonto",
    "Bitetto",
    "Bisceglie",
    "Biella",
    "Biassono",
    "Bernalda",
    "Bergamo",
    "Benevento",
    "Belluno",
    "Battipaglia",
    "Bastia umbra",
    "Bassano del Grappa",
    "Barra",
    "Baronissi",
    "Barletta",
    "Bari",
    "Bareggio",
    "Baranzate",
    "Bagnolo Mella",
    "Bagnoli",
    "Bacoli",
    "Azzano Decimo",
    "Avezzano",
    "Aversa",
    "Avellino",
    "Asti",
    "Ascoli Piceno",
    "Arzignano",
    "Arzano",
    "Artena",
    "Arona",
    "Arluno",
    "Ariccia",
    "Arezzo",
    "Arese",
    "Arenzano",
    "Ardea",
    "Arcore",
    "Arco",
    "Aprilia",
    "Apricena",
    "Aosta",
    "Anzio",
    "Anguillara Sabazia",
    "Angri",
    "Andria",
    "Ancona",
    "Alzano Lombardo",
    "Altavilla Vicentina",
    "Altamura",
    "Alpignano",
    "Alghero",
    "Alessandria",
    "Albino",
    "Albignasego",
    "Albenga",
    "Albano Laziale",
    "Alba",
    "Alatri",
    "Alassio",
    "Agropoli",
    "Agrate Brianza",
    "Agliana",
    "Afragola",
    "Adria",
    "Adelfia",
    "Acqui Terme",
    "Acquaviva delle Fonti",
    "Acilia-Castel Fusano-Ostia Antica",
    "Acerra",
    "Abbiategrasso",
    "Abano Terme",
    "Rivazzurra",
    "Ponzano",
    "Spinea-Orgnano",
    "Verbania",
    "Pieve Emanuele",
    "Osio Sotto",
    "Lumezzane",
    "Beccacivetta-Azzano",
    "Romano d'Ezzelino",
    "Monte Argentario",
    "Guidonia Montecelio",
    "Cervinara",
    "Lamezia Terme",
    "Cardano al Campo",
    "Caronno Pertusella",
    "Cassano Magnago",
    "Settimo Milanese",
    "Concesio",
    "San Cipriano d'Aversa",
    "San Felice A Cancello",
    "San Nicola la Strada",
    "Crispano",
    "Pollena Trocchia",
    "Quarto",
    "Tremestieri Etneo",
    "Santena",
    "Vinovo",
    "Casagiove",
    "Orta di Atella",
    "San Marcellino",
    "Teverola",
    "Casavatore",
    "Volla",
    "Santa Maria La Carità",
    "Bellizzi",
    "Alba Adriatica",
    "Gravina di Catania",
    "Lusciano",
    "Parete",
    "Piedimonte Matese",
    "Cesano Boscone",
    "Cesate",
    "Porto Viro",
    "Tor Lupara",
    "Torvaianica",
    "Casal Palocco",
    "Villa Adriana",
    "Bellaria-Igea Marina",
    "Villanova",
    "Marina di Ardea-Tor San Lorenzo",
    "San Paolo",
    "Monterusciello",
    "Romano Banco",
    "Casa Santa",
    "Arpino",
    "Paolo VI",
    "Breo",
    "Progresso",
    "Mejaniga",
    "La Massimina-Casal Lumbroso",
    "Chiugiana-La Commenda",
    "Corigliano Scalo",
    "Stella",
    "San Carlo All'Arena",
    "Chiaia",
    "Chiaiano",
    "Vicaria",
    "San Ferdinando",
    "Pendino",
    "Arenella",
    "Avvocata",
    "Montecalvario",
    "Scampia",
    "San Pietro a Patierno",
    "San Lorenzo",
]

export const arrCittà = arrCittàRaw.sort((a, b) => {
    if (a < b) {
        return -1
    } else if (a > b) {
        return 1
    } else {
        return 0
    }
})

export const arrTestoUnico = [
    "-",
    "Testo unico accise",
    "Testo unico apprendistato",
    "Testo unico avvocatura dello Stato",
    "Testo unico bancario",
    "Testo unico boschi e foreste",
    "Testo unico commercio",
    "Testo unico degli impiegati civili dello Stato",
    "Testo unico dei servizi di media audiovisivi e radiofonici",
    "Testo unico delle disposizioni sulla promulgazione delle leggi",
    "Testo unico delle leggi sugli interventi nel Mezzogiorno",
    "Testo unico delle leggi sulla Corte dei Conti",
    "Testo unico delle leggi sulla pesca",
    "Testo unico delle leggi sulle acque e sugli impianti elettrici",
    "Testo unico documentazione amministrativa",
    "Testo unico edilizia",
    "Testo unico elettorale del Senato della Repubblica",
    "Testo unico elettorale della Camera dei deputati",
    "Testo unico enti locali",
    "Testo unico espropriazione",
    "Testo unico finanziario",
    "Testo unico immigrazione",
    "Testo unico imposta registro",
    "Testo unico imposte sui redditi",
    "Testo unico in materia di casellario giudiziale",
    "Testo unico in materia di pensioni di guerra",
    "Testo unico in materia di piante officinali",
    "Testo unico in materia doganale",
    "Testo unico in materia postale",
    "Testo unico IVA",
    "Testo unico leggi di pubblica sicurezza",
    "Testo unico maternità e paternità",
    "Testo unico pubblico impiego",
    "Testo unico scuola",
    "Testo unico società a partecipazione pubblica",
    "Testo unico spese di giustizia",
    "Testo unico stupefacenti",
    "Testo unico su sequestro, pignoramento e cessione degli stipendi dei pubblici dipendenti",
    "Testo unico successioni e donazioni",
    "Testo unico sull'assicurazione degli infortuni sul lavoro",
    "Testo unico sulle imposte ipotecaria e catastale",
    "Testo unico sulle leggi sanitarie"
]