GM_consulting.glossarywords.insertMany([
  {
    name: "dolor",
    meaning: "Letteralmente 'Sofferenza' in latino.",
    reference: "Riferimenti",
  },
  {
    name: "privacy",
    meaning:
      "Il termine inglese privacy (pronuncia britannica: [ˈpɹɪvəsi], statunitense: [ˈpɹaɪvəsi] e italiana: /'praivasi/), in italiano riservatezza o privatezza, indica - nel lessico giuridico-legale - il diritto alla riservatezza della vita privata di una persona.",
    reference: "Riferimenti",
  },
  {
    name: "che",
    meaning: "congiunzione semplice",
    reference: "Riferimenti",
  },
]);

GM_consulting.tests.insertMany([
  {
    title: "TEST N°1 DI VERIFICA DELL’APPRENDIMENTO",
    subtitle: "(RISPOSTA MULTIPLA, SCELTA SINGOLA)",
    multipleAnswer: false,
    pointsSystem: false,
    instructions:
      "gli item elencati di seguito prevedono una sola risposta esatta, il test non è valutativo ma ha come obiettivo primario la verifica dell’apprendimento ai fini del proseguimento del percorso formativo identificato.",
    timeLimit: 900000,
    questions: [
      {
        text: "La norma in vigore dal 25 maggio 2018, è identificata come:",
        answers: [
          {
            text: "D.Lgs. 81/2008",
            selected: false,
            value: false,
          },
          {
            text: "Regolamento N°679/2016",
            selected: false,
            value: true,
          },
          {
            text: "D. Lgs. 196/2003",
            selected: false,
            value: false,
          },
          {
            text: "D.lgs N°675/96",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "La nuova normativa europea in materia di protezione dei dati si applica a:",
        answers: [
          {
            text: "Solo alle aziende italiane che trattano dati di cittadini europei",
            selected: false,
            value: false,
          },
          {
            text: "Anche alle aziende extraeuropee che propongono prodotti e servizi a cittadini europei",
            selected: false,
            value: true,
          },
          {
            text: "Solo alle aziende europee che trattano dati di aziende europee",
            selected: false,
            value: false,
          },
          {
            text: "Solo alle aziende europee che trattano dati di cittadini europei e cittadini non europei",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "La normativa europea in ambito di protezione dei dati si applica a:",
        answers: [
          {
            text: "Anche ai dati per l’esercizio di attività a carattere personale o domestico",
            selected: false,
            value: false,
          },
          {
            text: "A trattamenti interamente o parzialmente automatizzati di dati personali e al trattamento non automatizzato di dati personali contenuti in un archivio",
            selected: false,
            value: true,
          },
          {
            text: "A trattamenti interamente o parzialmente automatizzati di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "Solo al trattamento automatizzato dei dati",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Definizione di “dato personale” (indicare più risposte esatte):",
        answers: [
          {
            text: "Un’immagine o un video di una persona",
            selected: false,
            value: false,
          },
          {
            text: "Un audio di una persona",
            selected: false,
            value: false,
          },
          {
            text: "I dati trattati da un Titolare appartenenti ad interessati non identificabili dal Titolare, ma identificabili solo da altri soggetti.",
            selected: false,
            value: false,
          },
          {
            text: "L’identificativo on line (IP) di un pc",
            selected: false,
            value: false,
          },
          {
            text: "I dati del GPS di un guidatore di taxi",
            selected: false,
            value: false,
          },
          {
            text: "Il nickname in un forum",
            selected: false,
            value: false,
          },
          {
            text: "I dati di una persona identificabile in modo indiretto",
            selected: false,
            value: false,
          },
          {
            text: "I dati di valutazione di un individuo stilati da un’altra persona",
            selected: false,
            value: false,
          },
          {
            text: "Tutti i precedenti",
            selected: false,
            value: true,
          },
        ],
      },
      {
        text: "Viene identificato come «dato sensibile»:",
        answers: [
          {
            text: "Il numero di cellulare",
            selected: false,
            value: false,
          },
          {
            text: "Lo stipendio percepito",
            selected: false,
            value: false,
          },
          {
            text: "La propria inclinazione sessuale",
            selected: false,
            value: true,
          },
          {
            text: "Tutti quelli sopra citati",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Tra i seguenti, sono inoltre da considerarsi «dati sensibili»:",
        answers: [
          {
            text: "Il nome ed il cognome da sposato/a",
            selected: false,
            value: false,
          },
          {
            text: "Il numero di telefono fisso",
            selected: false,
            value: false,
          },
          {
            text: "La propria password",
            selected: false,
            value: false,
          },
          {
            text: "Nessuna di quelle sopra",
            selected: false,
            value: true,
          },
        ],
      },
      {
        text: "Cosa d’intende per pseudonimizzazione?",
        answers: [
          {
            text: "Il processo con cui i dati trattati non possano più essere attribuiti a un interessato specifico senza l'utilizzo di informazioni aggiuntive, a condizione che tali informazioni aggiuntive siano conservate separatamente e soggette a misure tecniche e organizzative.",
            selected: false,
            value: true,
          },
          {
            text: "Il processo con cui i dati trattati non possano più essere attribuiti a un interessato specifico perché sono resi anonimi attraverso delle particolari tecniche informatiche sicure che impediscono la ricostruzione dell’archivio di base.",
            selected: false,
            value: false,
          },
          {
            text: "Il processo con cui i dati trattati non possano più essere attribuiti a un interessato specifico perché sono resi anonimi attraverso delle particolari tecniche informatiche o procedure organizzative.",
            selected: false,
            value: false,
          },
          {
            text: "Nessuna delle precedenti.",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Indicare quale dei seguenti non è da considerare un “trattamento di dati”?",
        answers: [
          {
            text: "L’adattamento di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "La consultazione di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "Il raffronto di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "L’interconnessione di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "L’estrazione di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "La distruzione di dati personali",
            selected: false,
            value: false,
          },
          {
            text: "Nessuna delle precedenti",
            selected: false,
            value: true,
          },
        ],
      },
      {
        text: "Una volta data ottenuto in maniera idonea ed adeguata il consenso al trattamento dei suoi dati:",
        answers: [
          {
            text: "Posso utilizzare i dati dell’interessato anche per altre finalità.",
            selected: false,
            value: false,
          },
          {
            text: "Posso utilizzare i dati dell’interessato solo per finalità simili a quelle indicate nell’informativa anche se nella stessa non sono esplicitamente indicate. Non necessito di un nuovo consenso.",
            selected: false,
            value: false,
          },
          {
            text: "Non posso utilizzare i dati dell’interessato per altre finalità, nemmeno se ottengo un nuovo consenso (per il principio della Privacy by design previsto dal Regolamento 2016/679)",
            selected: false,
            value: false,
          },
          {
            text: "Posso utilizzare i dati dell’interessato, senza ulteriore consenso, solo per finalità di archiviazione nel pubblico interesse o per finalità statistiche o di ricerca scientifica.",
            selected: false,
            value: true,
          },
        ],
      },
      {
        text: "La minimizzazione prevede che:",
        answers: [
          {
            text: "I dati cartacei siano conservati in tanti archivi di piccole dimensioni (dimensioni minime) piuttosto che in un unico archivio generale che se violato determina la perdita di tutti i dati.",
            selected: false,
            value: false,
          },
          {
            text: "Di evitare che vi sia l’identificabilità dell’interessato nel caso in cui il trattamento non lo richieda raccogliendo solo quei dati che sono strettamente necessari al trattamento.",
            selected: false,
            value: true,
          },
          {
            text: "Comunicare i dati personali trattati a poche persone (“al minimo dei lavoratori necessari per l’esecuzione del trattamento”) così da diminuire la probabilità del rischio di diffusione dei dati.",
            selected: false,
            value: false,
          },
          {
            text: "Permettere l’accesso ai dati digitali a pochi account con il massimo dei privilegi.",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "I dati vanno conservati:",
        answers: [
          {
            text: "Solo per il tempo strettamente necessario per le finalità del trattamento.",
            selected: false,
            value: true,
          },
          {
            text: "Al massimo per 10 anni, poi è necessario un nuovo consenso esplicito",
            selected: false,
            value: false,
          },
          {
            text: "I dati personali senza limiti, i dati sensibili al massimo per 5 anni",
            selected: false,
            value: false,
          },
          {
            text: "Al massimo per 5 anni, poi è necessario un nuovo consenso esplicito",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Il Titolare del trattamento è:",
        answers: [
          {
            text: "Il soggetto che determina finalità e mezzi di trattamento ed il profilo della sicurezza",
            selected: false,
            value: true,
          },
          {
            text: "Il soggetto che determina le finalità del trattamento",
            selected: false,
            value: false,
          },
          {
            text: "Il soggetto che raccoglie i dati dell’interessato presso l’interessato o il altro modo",
            selected: false,
            value: false,
          },
          {
            text: "D. Il soggetto che determina i mezzi del trattamento e le misure di sicurezza",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Chi è, secondo il Regolamento, il «responsabile» al trattamento dei dati:. Il Responsabile del trattamento può nominare:",
        answers: [
          {
            text: "Il dipendente, o tirocinante o volontario, dell’ente che tratta i dati ed è responsabile di quello che succede ai dati stessi.",
            selected: false,
            value: false,
          },
          {
            text: "Sempre e solo il Rappresentante Legale dell’Ente, responsabile delle misure di sicurezza.",
            selected: false,
            value: false,
          },
          {
            text: "Una persona fisica o una persona giuridica a cui spettano le decisioni in ordine alle finalità, alle modalità e agli strumenti utilizzati, ivi compreso il profilo della sicurezza",
            selected: false,
            value: false,
          },
          {
            text: "Una persona fisica o una persona giuridica preposto dal titolare al trattamento dei dati.",
            selected: false,
            value: true,
          },
        ],
      },
      {
        text: "Il Responsabile del trattamento può nominare:",
        answers: [
          {
            text: "altri responsabili in modo indipendente a patto che sia formalizzato per iscritto",
            selected: false,
            value: false,
          },
          {
            text: "altri Responsabili in forza di un’autorizzazione del Titolare ma deve sempre comunicare al Titolare i nominativi dei subresponsabili",
            selected: false,
            value: true,
          },
          {
            text: "altri Responsabili solo se autorizzato in modo specifico, per ogni sub responsabile, dal Titolare del trattamento",
            selected: false,
            value: false,
          },
          {
            text: "altri Responsabili definendo finalità diverse da quelle indicate dal Titolare",
            selected: false,
            value: false,
          },
        ],
      },
      {
        text: "Il Data Protection Officer o DPO o Responsabile della Protezione dei dati deve:",
        answers: [
          {
            text: "Effettuare delle visite ispettive, su mandato del Garante della Privacy, per verificare come avvengono i trattamenti dei dati.",
            selected: false,
            value: false,
          },
          {
            text: "Informare e fornire consulenza al Titolare del trattamento e sorvegliare sull’osservanza del Regolamento da parte del Titolare",
            selected: false,
            value: true,
          },
          {
            text: "Implementare le misure informatiche richieste dal Titolare per garantire la sicurezza dei sistemi informativi",
            selected: false,
            value: false,
          },
          {
            text: "D. Gestire i dati che riceve dal Titolare e implementare le misure di sicurezza richieste dallo stesso, perseguendo le finalità definite dal Titolare e scegliendo i mezzi per perseguirle.",
            selected: false,
            value: false,
          },
        ],
      },
    ],
  },
  {
    title: "TEST DEBUGGING",
    subtitle: "(only for debugging)",
    multipleAnswer: false,
    pointsSystem: false,
    instructions: "fake instructions",
    timeLimit: 9000000,
    questions: [
      {
        text: "Fake question 1: two right answers",
        answers: [
          {
            text: "wrong answer",
            selected: false,
            value: false,
            points: 0,
          },
          {
            text: "right answer A",
            selected: false,
            value: true,
            points: 1,
          },
          {
            text: "wrong answer",
            selected: false,
            value: false,
            points: 0,
          },
          {
            text: "right answer B",
            selected: false,
            value: false,
            points: 1,
          },
        ],
      },
      {
        text: "Fake question 2: three right answers.",
        answers: [
          {
            text: "wrong answer",
            selected: false,
            value: false,
            points: 0,
          },
          {
            text: "right answer A",
            selected: false,
            value: true,
            points: 1,
          },
          {
            text: "right answer B",
            selected: false,
            value: true,
            points: 1,
          },
          {
            text: "right answer C (+)",
            selected: false,
            value: true,
            points: 2,
          },
        ],
      },
      {
        text: "Fake question 3: one right asnwer",
        answers: [
          {
            text: "wrong answer",
            selected: false,
            value: false,
          },
          {
            text: "right answer",
            selected: false,
            value: true,
            points: 2,
          },
          {
            text: "wrong answer",
            selected: false,
            value: false,
          },
          {
            text: "wrong answer",
            selected: false,
            value: false,
          },
        ],
      },
    ],
  },
]);

GM_consulting.consultations.insertMany([
  {
    id: "0",
    img: "",
    ita: {
      title: "Tutela dei Dati Personali",
      description: "Descrizione di: Tutela dei Dati Personali",
      content:
        "<ul><li>Modelli organizzativi e sistemi di <strong>gestione privacy</strong></li><li>Integrazione tra Sistemi di gestione privacy e Sistemi di gestione antiriciclaggio <em>(D.Lgs. 231/07)</em></li><li>Servizi di Responsabile della protezione dati <strong>(DPO)</strong></li><li>Analisi e valutazione rischi</li><li>Procedure per la valutazione di impatto</li><li>Censimento e mappatura dei trattamenti</li><li><strong>Privacy policy web</strong> e <strong>cookie policies</strong></li><li>Nomine e informative per i vari trattamenti aziendali</li><li>Impianto del registro dei trattamenti</li><li>Adeguamento al <strong>GDPR</strong> dei trattamenti di videosorveglianza e geolocalizzazione. Accordi sindacali e richiesta di autorizzazioni alla <strong>Direzione Regionale del Lavoro</strong></li><li>Procedure per la gestione del trattamento dati per il personale dipendente</li><li>Procedure per la gestione del trattamento dati sanitari</li><li>Analisi dei processi di conservazione dei dati personali e implementazione di <strong>Data Retention Policies</strong></li><li>Procedure e disciplinari interni la realizzazione di un sistema di <strong>whistleblowing</strong></li><li>Disciplinari interni per l&rsquo;utilizzo di dispositivi elettronici aziendali, l&rsquo;utilizzo della posta elettronico e l&rsquo;uso di internet</li><li>Audit di terze parti e qualifica dei fornitori (responsabili del trattamento)</li><li><strong>Stress accountability test</strong></li><li>Assistenza e supporto in occasione di attivit&agrave; ispettive degli organi di controllo</li></ul>",
    },
    eng: {
      title: "Personal Data Protection",
      description: "Personal Data Protection description",
      content: "Personal Data Protection content",
    },
  },
  {
    id: "1",
    img: "",
    ita: {
      title: "Antiriclaggio",
      description: "Descrizione di: consulenza antiriciclaggio",
      content: "Contenuto di: consulenza antiriciclaggio",
    },
    eng: {
      title: "Anti-money Laundering",
      description: "Anti-money Laundering consultation description",
      content: "Anti-money Laundering consultation content",
    },
  },
]);

GM_consulting.contents.insertMany([
  {
    title: "chiSiamo",
    firstCol: {
      ita: "Per affrontare un mondo ricco di incognite, incertezze e rischi, le aziende hanno bisogno di professionisti che operino in modo nuovo, utilizzando un set di strumenti differenziati, in grado di adeguare l’azione di supporto al cliente alle singole realtà organizzative. Grazie alle competenze maturate in vari ambiti disciplinari, alla pluriennale esperienza in ambito formativo e alla rete di partner di assoluto prestigio, io Gaetano Mastropierro e la mia azienda MTS siamo in grado di offrire qualcosa di più di una mera indicazione standardizzata.",
      eng: "To face a world full of unknowns, uncertainties and risks, companies need professionals who work in a new way, using a set of differentiated tools, able to adapt the customer support action to the individual organizational realities. Thanks to the skills gained in various disciplinary fields, to the many years of experience in the training field and to the network of partners of absolute prestige, I Gaetano Mastropierro and my company MTS are able to offer something more than a mere standardized indication.",
    },
    secondCol: {
      ita: "Sono un libero professionista e sono cofondatore di MTS, una società relativamente giovane si, circa 2 anni e mezzo, ma  che vanta collaborazione con grandi aziende di svariati settori. Oggi più che mai il mercato richiede specialisti affidabili, capaci di supportare le imprese nel conseguimento e nel mantenimento di una conformità normativa tenendo contro delle peculiarità gestionali, organizzative e culturali di ciascuna realtà. Mettere in grado i nostri clienti di riconoscere tempestivamente i segnali di criticità così da anticipare o contenere l’”inatteso”, costituisce la forza distintiva di un servizio consulenziale efficace. Io e la mia azienda vogliamo  che i nostri clienti diventino organizzazioni “ad alta affidabilità” (HRO), in grado cioè di anticipare i pericoli e correggere gli errori prima che la situazione si aggravi.",
      eng: 'I am a freelancer and I am co-founder of MTS, a relatively young company, about 2 and a half years old, but which boasts collaboration with large companies in various sectors. Today, more than ever, the market requires reliable specialists, capable of supporting companies in achieving and maintaining regulatory compliance taking into account the managerial, organizational and cultural peculiarities of each reality. Enabling our customers to promptly recognize critical signs so as to anticipate or contain the "unexpected" is the distinctive strength of an effective consulting service. My company and I want our customers to become “high reliability” organizations (HROs), able to anticipate dangers and correct errors before the situation escalates.',
    },
  },
]);

GM_consulting.articleTopics.insertMany([
  {
    name: {
      ita: "Privacy",
      eng: "Privacy",
    },
    id: "1",
  },
  {
    name: {
      ita: "Antiriciclaggio",
      eng: "Anti-money Laundering",
    },
    id: "2",
  },
  {
    name: {
      ita: "Anticorruzione",
      eng: "Anti-corruption",
    },
    id: "3",
  },
  {
    name: {
      ita: "GDPR",
      eng: "GDPR",
    },
    id: "4",
  },
  {
    name: {
      ita: "Privacy Policy",
      eng: "Privacy Policy",
    },
    id: "5",
  },
  {
    name: {
      ita: "Cookie Policy",
      eng: "Cookie Policy",
    },
    id: "6",
  },
]);

GM_consulting.articles.insertMany([
  {
    id: "0",
    glossary: ["privacy"],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: [
      {
        src: "/articoli/url-preview-img-2.png",
        position: "right",
        size: "sm",
        margin: " mt-1 mb-1 ml-2",
      },
      {
        src: "/articoli/url-preview-img-1.png",
        position: "left",
        size: "md",
        margin: " mt-1 mb-1 mr-2",
      },
      {
        src: "/articoli/url-preview-img-4.png",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
    ],
    ita: {
      topic: "Privacy",
      tags: ["#antiriciclaggio", "#anticorruzione", "#privacy"],
      title: "Prenotazioni on line di servizi sanitari: c’è ancora molto da fare. Il rischio di essere sottoposti ad attività ispettive online.",
      subtitle: "Le recenti sanzioni applicate dalla CNIL in Francia a due medici evidenziano aspetti che potrebbero riguardare il settore sanitario italiano. ",
      content: [
        "Il significato di privacy nel tempo si &egrave; evoluto anche in relazione all'evoluzione tecnologica che dai tempi di Warren e Brandeis (fine&nbsp;XIX secolo) &egrave; intercorsa. Inizialmente riferito alla sfera della vita privata, negli ultimi decenni ha subito un'evoluzione estensiva, arrivando ad indicare il diritto al controllo sui propri&nbsp;dati personali.<sup id=\"cite_ref-11\" class=\"reference\"></sup>&nbsp;Quindi, il significato odierno, di&nbsp;<em>privacy</em>, comunemente, &egrave; relativo al diritto della persona di controllare che le informazioni che la riguardano vengano trattate o guardate da altri solo in caso di necessit&agrave;.La&nbsp;<em>privacy</em>&nbsp;non va confusa nemmeno con la solitudine, e questa non va confusa con l'abbandono, in quanto sussiste una profonda differenza, infatti, tra &laquo;l'esser soli&raquo;, &laquo;l'esser lasciati soli&raquo; e &laquo;l'esser lasciati in condizioni di non-autosufficienza&raquo; con&nbsp;handicap&nbsp;senza essere capaci n&eacute; di intendere n&eacute; di volere. Il termine avrebbe anche un'accezione culturale: secondo alcuni ricercatori il concetto di&nbsp;<em>privacy</em>&nbsp;distingue la cultura Anglo-americana da quella Europea occidentale, come quella Italiana, Tedesca o Francese. Tuttavia si hanno troppi punti in comune tra le due soprattutto dal punto di vista del ruolo delle informazioni personali all'interno della societ&agrave;.<sup id=\"cite_ref-12\" class=\"reference\"></sup>",
        "Il diritto alla privacy non va confuso con il diritto al segreto, anch'esso finalizzato a tutelare un'area riservata della vita privata ma che per qualche motivo comprenda elementi comunque conosciuti da alcune persone: il medico, ad esempio, &egrave; sicuramente consapevole dello stato di salute del proprio paziente, ma ha il dovere di mantenere il segreto professionale sulle notizie di cui &egrave; a conoscenza.Il diritto alla privacy non &egrave; nemmeno interamente sovrapponibile al diritto alla protezione dei dati personali (cio&egrave; alla protezione da monitoraggio continuo, previsione dei comportamenti, profilazione degli individui) che nasce come corollario del diritto alla riservatezza.[13]La diffusione delle nuove tecnologie a partire dal XXI secolo ha contribuito ad un assottigliamento della barriera della privacy, ad esempio la tracciabilit&agrave; dei cellulari o la relativa facilit&agrave; a reperire gli indirizzi di posta elettronica delle persone, che pu&ograve; dar luogo, ad esempio, al fenomeno dello spamming, pubblicit&agrave; indesiderata. Anche la geolocalizzazione degli smartwatch, combinata con funzioni in questi contenute, come il cardiofrequenzimetro, pu&ograve; impattare in modo significativo sulla privacy, permettendo ad aziende di marketing di monitorare l'utente nelle sue abitudini di consumo e gusti personali attraverso tecniche di pubblicit&agrave; comportamentale, cio&egrave; una raccolta delle informazioni personali degli utenti come mezzo di marketing per proporre pubblicit&agrave; targetizzate, come evidenziato da Federprivacy nel 2015, e confermato da uno studio condotto dall'Universit&agrave; di Pisa in collaborazione con l'Universit&agrave; dell'Essex, e l'Harvard Medical School.",
        "La digitalizzazione delle immagini contribuisce ad una continua e progressiva riduzione della riservatezza e da difficolt&agrave; nella sua tutela: condividere un'immagine o un video on-line su internet comporta la perdita di controllo sul materiale inserito. Ad esempio il sexting - condivisione di fotografie a carattere erotico prevalentemente sui social network - comporta la totale impossibilit&agrave; di nasconderla potendo essere scaricata da altri utenti e reimmessa in Rete in qualunque altro momento. Analoghi problemi sorgono allorch&eacute; vi siano video che in qualche modo siano lesivi della privacy o in qualche modo lesivi di altre persone, soprattutto se di minore et&agrave;.Il 28 gennaio &egrave; celebrata da diversi paesi nel mondo la Giornata europea della protezione dei dati personali, istituita dal Consiglio d'Europa.",
      ],
    },
    eng: {
      topic: "Privacy",
      tags: ["#antimoneylaundering", "#anticorruption", "#privacy"],
      title: "title article 1",
      subtitle: "subtitle article 1",
      content: [
        "Il significato di privacy nel tempo si &egrave; evoluto anche in relazione all'evoluzione tecnologica che dai tempi di Warren e Brandeis (fine&nbsp;XIX secolo) &egrave; intercorsa. Inizialmente riferito alla sfera della vita privata, negli ultimi decenni ha subito un'evoluzione estensiva, arrivando ad indicare il diritto al controllo sui propri&nbsp;dati personali.<sup id=\"cite_ref-11\" class=\"reference\"></sup>&nbsp;Quindi, il significato odierno, di&nbsp;<em>privacy</em>, comunemente, &egrave; relativo al diritto della persona di controllare che le informazioni che la riguardano vengano trattate o guardate da altri solo in caso di necessit&agrave;.La&nbsp;<em>privacy</em>&nbsp;non va confusa nemmeno con la solitudine, e questa non va confusa con l'abbandono, in quanto sussiste una profonda differenza, infatti, tra &laquo;l'esser soli&raquo;, &laquo;l'esser lasciati soli&raquo; e &laquo;l'esser lasciati in condizioni di non-autosufficienza&raquo; con&nbsp;handicap&nbsp;senza essere capaci n&eacute; di intendere n&eacute; di volere. Il termine avrebbe anche un'accezione culturale: secondo alcuni ricercatori il concetto di&nbsp;<em>privacy</em>&nbsp;distingue la cultura Anglo-americana da quella Europea occidentale, come quella Italiana, Tedesca o Francese. Tuttavia si hanno troppi punti in comune tra le due soprattutto dal punto di vista del ruolo delle informazioni personali all'interno della societ&agrave;.<sup id=\"cite_ref-12\" class=\"reference\"></sup>",
        "Il diritto alla privacy non va confuso con il diritto al segreto, anch'esso finalizzato a tutelare un'area riservata della vita privata ma che per qualche motivo comprenda elementi comunque conosciuti da alcune persone: il medico, ad esempio, &egrave; sicuramente consapevole dello stato di salute del proprio paziente, ma ha il dovere di mantenere il segreto professionale sulle notizie di cui &egrave; a conoscenza.Il diritto alla privacy non &egrave; nemmeno interamente sovrapponibile al diritto alla protezione dei dati personali (cio&egrave; alla protezione da monitoraggio continuo, previsione dei comportamenti, profilazione degli individui) che nasce come corollario del diritto alla riservatezza.[13]La diffusione delle nuove tecnologie a partire dal XXI secolo ha contribuito ad un assottigliamento della barriera della privacy, ad esempio la tracciabilit&agrave; dei cellulari o la relativa facilit&agrave; a reperire gli indirizzi di posta elettronica delle persone, che pu&ograve; dar luogo, ad esempio, al fenomeno dello spamming, pubblicit&agrave; indesiderata. Anche la geolocalizzazione degli smartwatch, combinata con funzioni in questi contenute, come il cardiofrequenzimetro, pu&ograve; impattare in modo significativo sulla privacy, permettendo ad aziende di marketing di monitorare l'utente nelle sue abitudini di consumo e gusti personali attraverso tecniche di pubblicit&agrave; comportamentale, cio&egrave; una raccolta delle informazioni personali degli utenti come mezzo di marketing per proporre pubblicit&agrave; targetizzate, come evidenziato da Federprivacy nel 2015, e confermato da uno studio condotto dall'Universit&agrave; di Pisa in collaborazione con l'Universit&agrave; dell'Essex, e l'Harvard Medical School.",
        "La digitalizzazione delle immagini contribuisce ad una continua e progressiva riduzione della riservatezza e da difficolt&agrave; nella sua tutela: condividere un'immagine o un video on-line su internet comporta la perdita di controllo sul materiale inserito. Ad esempio il sexting - condivisione di fotografie a carattere erotico prevalentemente sui social network - comporta la totale impossibilit&agrave; di nasconderla potendo essere scaricata da altri utenti e reimmessa in Rete in qualunque altro momento. Analoghi problemi sorgono allorch&eacute; vi siano video che in qualche modo siano lesivi della privacy o in qualche modo lesivi di altre persone, soprattutto se di minore et&agrave;.Il 28 gennaio &egrave; celebrata da diversi paesi nel mondo la Giornata europea della protezione dei dati personali, istituita dal Consiglio d'Europa.",
      ],
    },
  },
  {
    id: "1",
    glossary: ["dolor"],
    date: "2020-12-26",
    authors: ["Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-2.png",
    images: [
      {
        src: "/articoli/imgProva1.jpg",
        position: "left",
        size: "md",
        margin: " mt-1 mb-1 mr-2",
      },
      {
        src: "/articoli/imgProva2.jpg",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
      {
        src: "/articoli/url-preview-img-4.png",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
    ],
    ita: {
      topic: "Privacy",
      tags: ["#curiosità", "#antiriciclaggio"],
      title: "titolo articolo 2",
      subtitle: "sottotitolo articolo 2",
      content: [
        "Paragrafo 1 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.\n        ",
        "Paragrafo 2 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.",
        "Paragrafo 3 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.",
      ],
    },
    eng: {
      topic: "Privacy",
      tags: ["#trivia", "#antimoneylaundering"],
      title: "title article 2",
      subtitle: "subtitle article 2",
      content: ["content article 2 - bla bla bla"],
    },
  },
  {
    id: "2",
    glossary: [],
    date: "2020-12-27",
    authors: ["Autore Esterno"],
    previewImg: "/articoli/url-preview-img-3.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 3",
      subtitle: "sottotitolo articolo 3",
      content: ["contenuto articolo 3 - bla bla bla"],
    },
    eng: {
      topic: "Privacy",
      tags: ["#privacy", "#international"],
      title: "title article 3",
      subtitle: "subtitle article 3",
      content: ["content article 3 - bla bla bla"],
    },
  },
  {
    id: "3",
    glossary: [],
    date: "2020-12-28",
    authors: ["Autore Esterno"],
    tags: ["#antiriciclaggio", "#anticorruzione"],
    previewImg: "/articoli/url-preview-img-4.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 4",
      subtitle: "sottotitolo articolo 4",
      content: ["contenuto articolo 4 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 4",
      subtitle: "subtitle article 4",
      content: ["content article 4 - bla bla bla"],
    },
  },
  {
    id: "4",
    glossary: [],
    date: "2020-12-29",
    authors: ["Autore Esterno"],
    previewImg: "/articoli/url-preview-img-5.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#internazionale", "#nazionale"],
      title: "titolo articolo 5",
      subtitle: "sottotitolo articolo 5",
      content: ["contenuto articolo 5 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#international", "#national"],
      title: "title article 5",
      subtitle: "subtitle article 5",
      content: ["content article 5 - bla bla bla"],
    },
  },
  {
    id: "5",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#nazionale", "#curiosità"],
      title: "titolo articolo 6",
      subtitle: "sottotitolo articolo 6",
      content: ["contenuto articolo 6 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#national", "#trivia"],
      title: "title article 6",
      subtitle: "subtitle article 6",
      content: ["content article 6 - bla bla bla"],
    },
  },
  {
    id: "6",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 7",
      subtitle: "sottotitolo articolo 7",
      content: ["contenuto articolo 7 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#antimoneylaundering", "#international"],
      title: "title article 7",
      subtitle: "subtitle article 7",
      content: ["content article 7 - bla bla bla"],
    },
  },
  {
    id: "7",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#anticorruzione", "#privacy"],
      title: "titolo articolo 8",
      subtitle: "sottotitolo articolo 8",
      content: ["contenuto articolo 8 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#anticorruption", "#privacy"],
      title: "title article 8",
      subtitle: "subtitle article 8",
      content: ["content article 8 - bla bla bla"],
    },
  },
  {
    id: "8",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 9",
      subtitle: "sottotitolo articolo 9",
      content: ["contenuto articolo 9 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 9",
      subtitle: "subtitle article 9",
      content: ["content article 9 - bla bla bla"],
    },
  },
  {
    id: "9",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 10",
      subtitle: "sottotitolo articolo 10",
      content: ["contenuto articolo 10 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#international"],
      title: "title article 10",
      subtitle: "subtitle article 10",
      content: ["content article 10 - bla bla bla"],
    },
  },
  {
    id: "10",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 11",
      subtitle: "sottotitolo articolo 11",
      content: ["contenuto articolo 11 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 11",
      subtitle: "subtitle article 11",
      content: ["content article 11 - bla bla bla"],
    },
  },
  {
    id: "11",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 12",
      subtitle: "sottotitolo articolo 12",
      content: ["contenuto articolo 12 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 12",
      subtitle: "subtitle article 12",
      content: ["content article 12 - bla bla bla"],
    },
  },
  {
    id: "12",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 13",
      subtitle: "sottotitolo articolo 13",
      content: ["contenuto articolo 13 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 13",
      subtitle: "subtitle article 13",
      content: ["content article 13 - bla bla bla"],
    },
  },
  {
    id: "13",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 14",
      subtitle: "sottotitolo articolo 14",
      content: ["contenuto articolo 14 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 14",
      subtitle: "subtitle article 14",
      content: ["content article 14 - bla bla bla"],
    },
  },
  {
    id: "14",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Davide Antinori"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 15",
      subtitle: "sottotitolo articolo 15",
      content: ["contenuto articolo 15 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 15",
      subtitle: "subtitle article 15",
      content: ["content article 15 - bla bla bla"],
    },
  },
  {
    id: "15",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 16",
      subtitle: "sottotitolo articolo 16",
      content: ["contenuto articolo 16 - bla bla bla"],
    },
    eng: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#international"],
      title: "title article 16",
      subtitle: "subtitle article 16",
      content: ["content article 16 - bla bla bla"],
    },
  },
  {
    id: "16",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 17",
      subtitle: "sottotitolo articolo 17",
      content: ["contenuto articolo 17 - bla bla bla"],
    },
    eng: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#international"],
      title: "title article 17",
      subtitle: "subtitle article 17",
      content: ["content article 17 - bla bla bla"],
    },
  },
]);

GM_consulting.reviews.insertMany([
  {
    id: "0",
    glossary: ["privacy"],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: [
      {
        src: "/articoli/url-preview-img-2.png",
        position: "right",
        size: "sm",
        margin: " mt-1 mb-1 ml-2",
      },
      {
        src: "/articoli/url-preview-img-1.png",
        position: "left",
        size: "md",
        margin: " mt-1 mb-1 mr-2",
      },
      {
        src: "/articoli/url-preview-img-4.png",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
    ],
    ita: {
      topic: "Privacy",
      tags: ["#antiriciclaggio", "#anticorruzione", "#privacy"],
      title: "Prenotazioni on line di servizi sanitari: c’è ancora molto da fare. Il rischio di essere sottoposti ad attività ispettive online.",
      subtitle: "Le recenti sanzioni applicate dalla CNIL in Francia a due medici evidenziano aspetti che potrebbero riguardare il settore sanitario italiano. ",
      content: [
        "Il significato di privacy nel tempo si &egrave; evoluto anche in relazione all'evoluzione tecnologica che dai tempi di Warren e Brandeis (fine&nbsp;XIX secolo) &egrave; intercorsa. Inizialmente riferito alla sfera della vita privata, negli ultimi decenni ha subito un'evoluzione estensiva, arrivando ad indicare il diritto al controllo sui propri&nbsp;dati personali.<sup id=\"cite_ref-11\" class=\"reference\"></sup>&nbsp;Quindi, il significato odierno, di&nbsp;<em>privacy</em>, comunemente, &egrave; relativo al diritto della persona di controllare che le informazioni che la riguardano vengano trattate o guardate da altri solo in caso di necessit&agrave;.La&nbsp;<em>privacy</em>&nbsp;non va confusa nemmeno con la solitudine, e questa non va confusa con l'abbandono, in quanto sussiste una profonda differenza, infatti, tra &laquo;l'esser soli&raquo;, &laquo;l'esser lasciati soli&raquo; e &laquo;l'esser lasciati in condizioni di non-autosufficienza&raquo; con&nbsp;handicap&nbsp;senza essere capaci n&eacute; di intendere n&eacute; di volere. Il termine avrebbe anche un'accezione culturale: secondo alcuni ricercatori il concetto di&nbsp;<em>privacy</em>&nbsp;distingue la cultura Anglo-americana da quella Europea occidentale, come quella Italiana, Tedesca o Francese. Tuttavia si hanno troppi punti in comune tra le due soprattutto dal punto di vista del ruolo delle informazioni personali all'interno della societ&agrave;.<sup id=\"cite_ref-12\" class=\"reference\"></sup>",
        "Il diritto alla privacy non va confuso con il diritto al segreto, anch'esso finalizzato a tutelare un'area riservata della vita privata ma che per qualche motivo comprenda elementi comunque conosciuti da alcune persone: il medico, ad esempio, &egrave; sicuramente consapevole dello stato di salute del proprio paziente, ma ha il dovere di mantenere il segreto professionale sulle notizie di cui &egrave; a conoscenza.Il diritto alla privacy non &egrave; nemmeno interamente sovrapponibile al diritto alla protezione dei dati personali (cio&egrave; alla protezione da monitoraggio continuo, previsione dei comportamenti, profilazione degli individui) che nasce come corollario del diritto alla riservatezza.[13]La diffusione delle nuove tecnologie a partire dal XXI secolo ha contribuito ad un assottigliamento della barriera della privacy, ad esempio la tracciabilit&agrave; dei cellulari o la relativa facilit&agrave; a reperire gli indirizzi di posta elettronica delle persone, che pu&ograve; dar luogo, ad esempio, al fenomeno dello spamming, pubblicit&agrave; indesiderata. Anche la geolocalizzazione degli smartwatch, combinata con funzioni in questi contenute, come il cardiofrequenzimetro, pu&ograve; impattare in modo significativo sulla privacy, permettendo ad aziende di marketing di monitorare l'utente nelle sue abitudini di consumo e gusti personali attraverso tecniche di pubblicit&agrave; comportamentale, cio&egrave; una raccolta delle informazioni personali degli utenti come mezzo di marketing per proporre pubblicit&agrave; targetizzate, come evidenziato da Federprivacy nel 2015, e confermato da uno studio condotto dall'Universit&agrave; di Pisa in collaborazione con l'Universit&agrave; dell'Essex, e l'Harvard Medical School.",
        "La digitalizzazione delle immagini contribuisce ad una continua e progressiva riduzione della riservatezza e da difficolt&agrave; nella sua tutela: condividere un'immagine o un video on-line su internet comporta la perdita di controllo sul materiale inserito. Ad esempio il sexting - condivisione di fotografie a carattere erotico prevalentemente sui social network - comporta la totale impossibilit&agrave; di nasconderla potendo essere scaricata da altri utenti e reimmessa in Rete in qualunque altro momento. Analoghi problemi sorgono allorch&eacute; vi siano video che in qualche modo siano lesivi della privacy o in qualche modo lesivi di altre persone, soprattutto se di minore et&agrave;.Il 28 gennaio &egrave; celebrata da diversi paesi nel mondo la Giornata europea della protezione dei dati personali, istituita dal Consiglio d'Europa.",
      ],
    },
    eng: {
      topic: "Privacy",
      tags: ["#antimoneylaundering", "#anticorruption", "#privacy"],
      title: "title article 1",
      subtitle: "subtitle article 1",
      content: [
        "Il significato di privacy nel tempo si &egrave; evoluto anche in relazione all'evoluzione tecnologica che dai tempi di Warren e Brandeis (fine&nbsp;XIX secolo) &egrave; intercorsa. Inizialmente riferito alla sfera della vita privata, negli ultimi decenni ha subito un'evoluzione estensiva, arrivando ad indicare il diritto al controllo sui propri&nbsp;dati personali.<sup id=\"cite_ref-11\" class=\"reference\"></sup>&nbsp;Quindi, il significato odierno, di&nbsp;<em>privacy</em>, comunemente, &egrave; relativo al diritto della persona di controllare che le informazioni che la riguardano vengano trattate o guardate da altri solo in caso di necessit&agrave;.La&nbsp;<em>privacy</em>&nbsp;non va confusa nemmeno con la solitudine, e questa non va confusa con l'abbandono, in quanto sussiste una profonda differenza, infatti, tra &laquo;l'esser soli&raquo;, &laquo;l'esser lasciati soli&raquo; e &laquo;l'esser lasciati in condizioni di non-autosufficienza&raquo; con&nbsp;handicap&nbsp;senza essere capaci n&eacute; di intendere n&eacute; di volere. Il termine avrebbe anche un'accezione culturale: secondo alcuni ricercatori il concetto di&nbsp;<em>privacy</em>&nbsp;distingue la cultura Anglo-americana da quella Europea occidentale, come quella Italiana, Tedesca o Francese. Tuttavia si hanno troppi punti in comune tra le due soprattutto dal punto di vista del ruolo delle informazioni personali all'interno della societ&agrave;.<sup id=\"cite_ref-12\" class=\"reference\"></sup>",
        "Il diritto alla privacy non va confuso con il diritto al segreto, anch'esso finalizzato a tutelare un'area riservata della vita privata ma che per qualche motivo comprenda elementi comunque conosciuti da alcune persone: il medico, ad esempio, &egrave; sicuramente consapevole dello stato di salute del proprio paziente, ma ha il dovere di mantenere il segreto professionale sulle notizie di cui &egrave; a conoscenza.Il diritto alla privacy non &egrave; nemmeno interamente sovrapponibile al diritto alla protezione dei dati personali (cio&egrave; alla protezione da monitoraggio continuo, previsione dei comportamenti, profilazione degli individui) che nasce come corollario del diritto alla riservatezza.[13]La diffusione delle nuove tecnologie a partire dal XXI secolo ha contribuito ad un assottigliamento della barriera della privacy, ad esempio la tracciabilit&agrave; dei cellulari o la relativa facilit&agrave; a reperire gli indirizzi di posta elettronica delle persone, che pu&ograve; dar luogo, ad esempio, al fenomeno dello spamming, pubblicit&agrave; indesiderata. Anche la geolocalizzazione degli smartwatch, combinata con funzioni in questi contenute, come il cardiofrequenzimetro, pu&ograve; impattare in modo significativo sulla privacy, permettendo ad aziende di marketing di monitorare l'utente nelle sue abitudini di consumo e gusti personali attraverso tecniche di pubblicit&agrave; comportamentale, cio&egrave; una raccolta delle informazioni personali degli utenti come mezzo di marketing per proporre pubblicit&agrave; targetizzate, come evidenziato da Federprivacy nel 2015, e confermato da uno studio condotto dall'Universit&agrave; di Pisa in collaborazione con l'Universit&agrave; dell'Essex, e l'Harvard Medical School.",
        "La digitalizzazione delle immagini contribuisce ad una continua e progressiva riduzione della riservatezza e da difficolt&agrave; nella sua tutela: condividere un'immagine o un video on-line su internet comporta la perdita di controllo sul materiale inserito. Ad esempio il sexting - condivisione di fotografie a carattere erotico prevalentemente sui social network - comporta la totale impossibilit&agrave; di nasconderla potendo essere scaricata da altri utenti e reimmessa in Rete in qualunque altro momento. Analoghi problemi sorgono allorch&eacute; vi siano video che in qualche modo siano lesivi della privacy o in qualche modo lesivi di altre persone, soprattutto se di minore et&agrave;.Il 28 gennaio &egrave; celebrata da diversi paesi nel mondo la Giornata europea della protezione dei dati personali, istituita dal Consiglio d'Europa.",
      ],
    },
  },
  {
    id: "1",
    glossary: ["dolor"],
    date: "2020-12-26",
    authors: ["Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-2.png",
    images: [
      {
        src: "/articoli/imgProva1.jpg",
        position: "left",
        size: "md",
        margin: " mt-1 mb-1 mr-2",
      },
      {
        src: "/articoli/imgProva2.jpg",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
      {
        src: "/articoli/url-preview-img-4.png",
        position: "center",
        size: "lg",
        margin: " mt-2 mb-2",
      },
    ],
    ita: {
      topic: "Privacy",
      tags: ["#curiosità", "#antiriciclaggio"],
      title: "titolo articolo 2",
      subtitle: "sottotitolo articolo 2",
      content: [
        "Paragrafo 1 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.\n        ",
        "Paragrafo 2 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.",
        "Paragrafo 3 - dolor uno due tre quattro cinque dolor sei sette otto nove dieci dolor;\n        dolor undici dodici tredici quattordici quindici dolor sedici diciassette diciotto diciannove venti dolor.",
      ],
    },
    eng: {
      topic: "Privacy",
      tags: ["#trivia", "#antimoneylaundering"],
      title: "title article 2",
      subtitle: "subtitle article 2",
      content: ["content article 2 - bla bla bla"],
    },
  },
  {
    id: "2",
    glossary: [],
    date: "2020-12-27",
    authors: ["Autore Esterno"],
    previewImg: "/articoli/url-preview-img-3.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 3",
      subtitle: "sottotitolo articolo 3",
      content: ["contenuto articolo 3 - bla bla bla"],
    },
    eng: {
      topic: "Privacy",
      tags: ["#privacy", "#international"],
      title: "title article 3",
      subtitle: "subtitle article 3",
      content: ["content article 3 - bla bla bla"],
    },
  },
  {
    id: "3",
    glossary: [],
    date: "2020-12-28",
    authors: ["Autore Esterno"],
    tags: ["#antiriciclaggio", "#anticorruzione"],
    previewImg: "/articoli/url-preview-img-4.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 4",
      subtitle: "sottotitolo articolo 4",
      content: ["contenuto articolo 4 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 4",
      subtitle: "subtitle article 4",
      content: ["content article 4 - bla bla bla"],
    },
  },
  {
    id: "4",
    glossary: [],
    date: "2020-12-29",
    authors: ["Autore Esterno"],
    previewImg: "/articoli/url-preview-img-5.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#internazionale", "#nazionale"],
      title: "titolo articolo 5",
      subtitle: "sottotitolo articolo 5",
      content: ["contenuto articolo 5 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#international", "#national"],
      title: "title article 5",
      subtitle: "subtitle article 5",
      content: ["content article 5 - bla bla bla"],
    },
  },
  {
    id: "5",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Anticorruzione",
      tags: ["#nazionale", "#curiosità"],
      title: "titolo articolo 6",
      subtitle: "sottotitolo articolo 6",
      content: ["contenuto articolo 6 - bla bla bla"],
    },
    eng: {
      topic: "Anti-money Laundering",
      tags: ["#national", "#trivia"],
      title: "title article 6",
      subtitle: "subtitle article 6",
      content: ["content article 6 - bla bla bla"],
    },
  },
  {
    id: "6",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 7",
      subtitle: "sottotitolo articolo 7",
      content: ["contenuto articolo 7 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#antimoneylaundering", "#international"],
      title: "title article 7",
      subtitle: "subtitle article 7",
      content: ["content article 7 - bla bla bla"],
    },
  },
  {
    id: "7",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#anticorruzione", "#privacy"],
      title: "titolo articolo 8",
      subtitle: "sottotitolo articolo 8",
      content: ["contenuto articolo 8 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#anticorruption", "#privacy"],
      title: "title article 8",
      subtitle: "subtitle article 8",
      content: ["content article 8 - bla bla bla"],
    },
  },
  {
    id: "8",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Antiriciclaggio",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 9",
      subtitle: "sottotitolo articolo 9",
      content: ["contenuto articolo 9 - bla bla bla"],
    },
    eng: {
      topic: "Anti-corruption",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 9",
      subtitle: "subtitle article 9",
      content: ["content article 9 - bla bla bla"],
    },
  },
  {
    id: "9",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 10",
      subtitle: "sottotitolo articolo 10",
      content: ["contenuto articolo 10 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#international"],
      title: "title article 10",
      subtitle: "subtitle article 10",
      content: ["content article 10 - bla bla bla"],
    },
  },
  {
    id: "10",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 11",
      subtitle: "sottotitolo articolo 11",
      content: ["contenuto articolo 11 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 11",
      subtitle: "subtitle article 11",
      content: ["content article 11 - bla bla bla"],
    },
  },
  {
    id: "11",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "GDPR",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 12",
      subtitle: "sottotitolo articolo 12",
      content: ["contenuto articolo 12 - bla bla bla"],
    },
    eng: {
      topic: "GDPR",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 12",
      subtitle: "subtitle article 12",
      content: ["content article 12 - bla bla bla"],
    },
  },
  {
    id: "12",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 13",
      subtitle: "sottotitolo articolo 13",
      content: ["contenuto articolo 13 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 13",
      subtitle: "subtitle article 13",
      content: ["content article 13 - bla bla bla"],
    },
  },
  {
    id: "13",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#anticorruzione"],
      title: "titolo articolo 14",
      subtitle: "sottotitolo articolo 14",
      content: ["contenuto articolo 14 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 14",
      subtitle: "subtitle article 14",
      content: ["content article 14 - bla bla bla"],
    },
  },
  {
    id: "14",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Davide Antinori"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Privacy Policy",
      tags: ["#antiriciclaggio", "#internazionale"],
      title: "titolo articolo 15",
      subtitle: "sottotitolo articolo 15",
      content: ["contenuto articolo 15 - bla bla bla"],
    },
    eng: {
      topic: "Privacy Policy",
      tags: ["#antimoneylaundering", "#anticorruption"],
      title: "title article 15",
      subtitle: "subtitle article 15",
      content: ["content article 15 - bla bla bla"],
    },
  },
  {
    id: "15",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 16",
      subtitle: "sottotitolo articolo 16",
      content: ["contenuto articolo 16 - bla bla bla"],
    },
    eng: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#international"],
      title: "title article 16",
      subtitle: "subtitle article 16",
      content: ["content article 16 - bla bla bla"],
    },
  },
  {
    id: "16",
    glossary: [],
    date: "2020-12-25",
    authors: ["Gaetano Mastropierro", "Alessandro Mastropierro"],
    previewImg: "/articoli/url-preview-img-1.png",
    images: ["url-preview-img-2.png", "url-preview-img-3.png", "url-preview-img-4.png"],
    ita: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#internazionale"],
      title: "titolo articolo 17",
      subtitle: "sottotitolo articolo 17",
      content: ["contenuto articolo 17 - bla bla bla"],
    },
    eng: {
      topic: "Cookie Policy",
      tags: ["#privacy", "#international"],
      title: "title article 17",
      subtitle: "subtitle article 17",
      content: ["content article 17 - bla bla bla"],
    },
  },
]);
